### ISSUE TITLE
可以用python来调用安装好的fasterwhispergui.exe来自动化吗？ 还是必须要再装pip的fasterwhispergui才行？

### ISSUE THREAD

**Issue by bk111** [CheshireCC/faster-whisper-GUI#100]
可以用python来调用安装好的fasterwhispergui.exe来自动化吗？ 还是必须要再装pip的fasterwhispergui才行？

**Comment by CheshireCC** [comment]
目前没有给启动参数 ，不清楚这方面的具体需求
如果是大批量的数据处理自动化的话，你能部署 python 环境，也应该就能部署 fw 的 python 版本。。。。。
