### ISSUE TITLE
有的时间轴尾部早于话音结束，该调哪个参数呢？

### ISSUE THREAD

**Issue by bk111** [CheshireCC/faster-whisper-GUI#101]
有这种参数吗 ？end_of_sentence_silence_duration

![faster-whisper](https://github.com/CheshireCC/faster-whisper-GUI/assets/28552217/f39fefc3-07ee-4d02-9026-ffcb404fe6ad)

**Comment by CheshireCC** [comment]
应该是使用了 whisperX 进行时间戳对齐导致的
whisperX 上目前没有针对给字母语言，比如 日语、中文 之类语言的比较好的 音素对齐模型，所以会出现时间戳早于语音段结束的现象，暂时没啥好办法，时间轴要求不高的话，就用 fw 本身的单词级时间戳来精确时间戳吧
另外，如果识别结果不完整导致的时间戳缩短，那么可以调整 VAD 相关参数如：概率阈值 等来调整效果

**Comment by CheshireCC** [comment]
应该是使用了 whisperX 进行时间戳对齐导致的
whisperX 上目前没有针对非字母语言，比如 日语、中文 之类语言的比较好的 音素对齐模型，所以会出现时间戳早于语音段结束的现象，暂时没啥好办法，时间轴要求不高的话，就用 fw 本身的单词级时间戳来精确时间戳吧
另外，如果识别结果不完整导致的时间戳缩短，那么可以调整 VAD 相关参数如：概率阈值 等来调整效果

**Comment by bk111** [comment]
> 应该是使用了 whisperX 进行时间戳对齐导致的 whisperX 上目前没有针对非字母语言，比如 日语、中文 之类语言的比较好的 音素对齐模型，所以会出现时间戳早于语音段结束的现象，暂时没啥好办法，时间轴要求不高的话，就用 fw 本身的单词级时间戳来精确时间戳吧 另外，如果识别结果不完整导致的时间戳缩短，那么可以调整 VAD 相关参数如：概率阈值 等来调整效果

https://huggingface.co/spaces/sanchit-gandhi/whisper-jax  上产生的字幕与语音是正常的，那faster-whisper-GUI能借用这些参数吗？
