### ISSUE TITLE
resample audio error   部分视频Demucs提示失败以及Transcription停在中途

### ISSUE THREAD

**Issue by LuoXin1995** [CheshireCC/faster-whisper-GUI#103]
部分MP4跑Demucs会提示失败，直接跑Transcription会停在中途，例如3600秒的视频跑到2400秒就不动了，gpu负载消失。
能跑完Demucs的MP4，用生成的._vocals.wav文件跑Transcription都不会出现报错。或者手动用FFmpeg把mp4转wav后再跑就没有问题了。
电脑是Win11，AMD5600G+32G+4060Ti16G，视频使用浏览器插件cococut录制模式下载，网课有上百个视频，其中有十多个会报错，可能插件下载的视频也有点问题。

报错部分日志
> current task: C:/LXData/Video NLP/课时86 20231208_03_ModelScope零样本生成式模型项目代码实现讲解二 2.mp4
> reasmple audio...
> 双声道音频
> resample audio data
> Invalid vDk0[1]: 0
> SBR reset failed. Switching SBR to pure upsampling mode.
> resample audio error:
> Frame does not match AudioFifo parameters.
> Traceback (most recent call last):
>   File "D:\VM\FasterWhisperGUI\faster_whisper_GUI\de_mucs.py", line 90, in run
> UnboundLocalError: local variable 'samples' referenced before assignment

下方是较完整的日志
> The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
> torchvision is not available - cannot save figures
> The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
> 
> faster_whisper_GUI: 0.6.7
> ==========2024-03-16_19:23:44==========
> ==========Start==========
> 
> current computer language region-format: zh_CN
> language: zh
> 
> ==========2024-03-16_19:23:47==========
> ==========LoadModel==========
> 
>     -model_size_or_path: D:/VM/whisper-large-v3-float32
>     -device: cuda
>     -device_index: 0
>     -compute_type: float32
>     -cpu_threads: 4
>     -num_workers: 1
>     -download_root: C:/Users/luoxi/.cache/huggingface/hub
>     -local_files_only: True
>     -use_v3_model: True
> 
> Load over
> D:/VM/whisper-large-v3-float32
> max_length:             448
> num_samples_per_token:  320
> time_precision:  0.02
> tokens_per_second:  50
> input_stride:  2
> 
> [Using V3 model, modify  number of mel-filters to 128]
> ==========2024-03-16_19:27:19==========
> ==========Demucs==========
> 
> output_path: 
> overlap: 1.0
> segment: 11.0
> stems: Vocals
> audio: ['C:/LXData/Video NLP/课时86 20231208_03_ModelScope零样本生成式模型项目代码实现讲解二 1.mp4']
> device: cuda
> download_path: D:\VM\FasterWhisperGUI\cache\hdemucs_high_trained.pt
> found existed model file
> Sample rate: 44100
> current task: C:/LXData/Video NLP/课时86 20231208_03_ModelScope零样本生成式模型项目代码实现讲解二 1.mp4
> reasmple audio...
> 双声道音频
> resample audio data
> samples shape:  (2, 56886272)
> separate sources...
> save files...
> sources_list: ['drums', 'bass', 'other', 'vocals']
> save file: C:/LXData/Video NLP\Vocals\课时86 20231208_03_ModelScope零样本生成式模型项目代码实现讲解二 1._vocals.wav
> current task: C:/LXData/Video NLP/课时86 20231208_03_ModelScope零样本生成式模型项目代码实现讲解二 2.mp4
> reasmple audio...
> 双声道音频
> resample audio data
> Invalid vDk0[1]: 0
> SBR reset failed. Switching SBR to pure upsampling mode.
> resample audio error:
> Frame does not match AudioFifo parameters.
> Traceback (most recent call last):
>   File "D:\VM\FasterWhisperGUI\faster_whisper_GUI\de_mucs.py", line 90, in run
> UnboundLocalError: local variable 'samples' referenced before assignment

==========2024-03-17_12:24:19==========
==========Process==========

redirect std output
vad_filter : False
Transcribes options:
    -audio : [''C:/LXData/课时100 20231210_06_LangchainChatGLM讲解一.mp4']
    -language : zh
    -task : False
    -beam_size : 10
    -best_of : 5
    -patience : 1.0
    -length_penalty : 0.8
    -temperature : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    -compression_ratio_threshold : 2.4
    -log_prob_threshold : -1.0
    -no_speech_threshold : 0.6
    -condition_on_previous_text : False
    -initial_prompt : 主要内容是简体中文的ai深度学习课程，包含少量英语
    -prefix : None
    -suppress_blank : True
    -suppress_tokens : [-1]
    -without_timestamps : False
    -max_initial_timestamp : 1.0
    -word_timestamps : False
    -prepend_punctuations : "'“¿([{-
    -append_punctuations : "'.。,，!！?？:：”)]}、
    -repetition_penalty : 1.0
    -no_repeat_ngram_size : 0
    -prompt_reset_on_temperature : 0.5
create transcribe process with 1 workers
start transcribe process
Invalid vDk0[1]: 0
SBR reset failed. Switching SBR to pure upsampling mode.
Traceback (most recent call last):
  File "D:\VM\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 357, in run
  File "D:\VM\FasterWhisperGUI\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\VM\FasterWhisperGUI\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\VM\FasterWhisperGUI\concurrent\futures\_base.py", line 458, in result
  File "D:\VM\FasterWhisperGUI\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\VM\FasterWhisperGUI\concurrent\futures\thread.py", line 58, in run
  File "D:\VM\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 226, in transcribe_file
  File "D:\VM\FasterWhisperGUI\faster_whisper\transcribe.py", line 294, in transcribe
  File "D:\VM\FasterWhisperGUI\faster_whisper\audio.py", line 52, in decode_audio
  File "D:\VM\FasterWhisperGUI\faster_whisper\audio.py", line 103, in _resample_frames
  File "D:\VM\FasterWhisperGUI\faster_whisper\audio.py", line 92, in _group_frames
  File "av\\audio\\fifo.pyx", line 30, in av.audio.fifo.AudioFifo.write
  File "av\\audio\\fifo.pyx", line 86, in av.audio.fifo.AudioFifo.write
ValueError: Frame does not match AudioFifo parameters.

**Comment by CheshireCC** [comment]
ok, 我会进行排查，

**Comment by CheshireCC** [comment]
失败的这两份文件均显示了同样的错误，数据本身的格式上可能存在一些问题，可能的解决方案：
1. `demucs` 使用 **44100Hz** 采样，使用其他工具将音频文件采样至 44100Hz
2. `faster-whisper` 使用 **16000Hz** 采样率，使用其他工具将音频文件采样至 16000Hz

其他排查需要提供数据进行测试

**Comment by LuoXin1995** [comment]
> 失败的这两份文件均显示了同样的错误，数据本身的格式上可能存在一些问题，可能的解决方案：
> 
> 1. `demucs` 使用 **44100Hz** 采样，使用其他工具将音频文件采样至 44100Hz
> 2. `faster-whisper` 使用 **16000Hz** 采样率，使用其他工具将音频文件采样至 16000Hz
> 
> 其他排查需要提供数据进行测试


非常感谢。
我仔细检查了源文件，是插件下载的视频有问题。

虽然手动用FFmpeg把mp4转wav后再跑就不会报错了，但仔细检查后发现这样生成的字幕部分正常，部分不正常，有些会比视频长度少几百秒甚至上千秒，所以程序就是应该报错的，以避免产生可能有问题的字幕，我手动处理产生了可能有缺陷的字幕是错误的做法。
我重新下载视频之后再跑就没有问题了。 

我是不是应该删除这个问题？

**Comment by CheshireCC** [comment]
你好，这种情况确实存在，下载的视频元数据可能不齐全，此时 `ffmpeg` 将会根据文件中存在的部分元数据和音视频文件本身来对视频时长进行推断 ，但是这样的推断不一定正确，如果本身还存在部分错误的元数据，那么就更可能会产生这种情况，这将会导致文件的实际持续时间和程序读取的时长并不一致，从而导致转换得到的音频文件时长短于或者长于视频内容，这种情况常见于一些不规范的流媒体网站或者下载工具
那么现在我将会关闭这个 issue
