### ISSUE TITLE
运行时报错，无法正常运行

### ISSUE THREAD

**Issue by BeginHuang** [CheshireCC/faster-whisper-GUI#104]
python3.10，每次运行的时候都会报如下错误：

TypeError: QProgressBar(parent: Optional[QWidget] = None): argument 1 has unexpected type 'MySplashScreen'

不清楚问题出在哪里

**Comment by BeginHuang** [comment]
这个问题已经解决，原因如下：
如果项目中使用的是 PySide2、PySide6 或者 PyQt6，需切换至 [PySide2](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/tree/PySide2)、[PySide6](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/tree/PySide6) 和 [PyQt6](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/tree/PyQt6) 分支下载对应的代码。
但是现在又出现了新的问题

**TypeError: 'HomePageNavigationinterface' object is not callable**

**Comment by CheshireCC** [comment]
新代码已经推送
