### ISSUE TITLE
中英文

### ISSUE THREAD

**Issue by ChenNiJK** [CheshireCC/faster-whisper-GUI#106]
你好 中英文翻译，左侧菜单不支持翻译吗
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/129843521/e6064385-cde9-4504-a88f-e083e4fa0604)

**Comment by CheshireCC** [comment]
由于 Python 类继承的特性有关的一些原因，这些被分别实现在子类和父类中的文本无法在 pyside6 中实现翻译
我会尽量寻找解决方案

**Comment by CheshireCC** [comment]
新版本已经修复
