### ISSUE TITLE
出现无法安装的问题

### ISSUE THREAD

**Issue by IRuemoI** [CheshireCC/faster-whisper-GUI#107]
![1](https://github.com/CheshireCC/faster-whisper-GUI/assets/67491846/7bfb6d04-e95e-45fe-915c-d7101664497f)

安装会提示无法读取安装包。5.7和7.0我都用管理员运行了都会出现这个问题，请教一下大佬。

**Comment by CheshireCC** [comment]
我自己是所有电脑上都不会出现这个问题，要不然试一下管理员权限运行安装包程序？

**Comment by IRuemoI** [comment]
有劳您费心了 你说的方法我之前试过都不行（包括修改文件所有者以及所有者权限） 我的临时解决方案是在别的电脑上安装 然后复制到我的笔记上。
所以应该是个例。
