### ISSUE TITLE
太卡了

### ISSUE THREAD

**Issue by kebinzhi** [CheshireCC/faster-whisper-GUI#109]
文件太大了，启动卡得很，运行时也经常卡，有没办法缩小体积。

实测同样是v3模型，转换效果不如 https://huggingface.co/spaces/sanchit-gandhi/whisper-jax 这个项目。

**Comment by CheshireCC** [comment]
启动慢是因为pytorch引擎的原因，没啥好办法
运行卡那么你需要升级下你的电脑配置了，毕竟我测试6年老笔记本甚至8年老本都不卡顿✨
