### ISSUE TITLE
请问一下声乐分离的功能，乐声如何合并在一起？

### ISSUE THREAD

**Issue by stx0821** [CheshireCC/faster-whisper-GUI#110]
现在的声乐分离功能是人声是可以分离出来，但是乐声却分为低音、鼓音以及其他这三个文件，如何在分离的时候三个文件合一，只分离出一个文件，而不是再往下分为三个文件，因为只有完整的乐声，感觉才是对大部分人有用的，可以用做卡拉ok的版本。

**Comment by CheshireCC** [comment]
因为使用了 demucs 的 4 通道方案，所以是分离成多个通道的音轨了，可以考虑后续版本中将其他音轨合并成一个输出

**Comment by CheshireCC** [comment]
0.7.6 新增 人声-背景声 二分的输出方式
