### ISSUE TITLE
有时候视频说话声音小的时候就识别不到。

### ISSUE THREAD

**Issue by sulutian** [CheshireCC/faster-whisper-GUI#112]
该如何解决

**Comment by CheshireCC** [comment]
尝试分离下声源，
增强之后再识别，这个技术就很专业了，跟公安搞物证鉴定似的，本来也很难，
毕竟声音太小人听都挺难的了，对人工智障来说还是太为难了

**Comment by sulutian** [comment]
Yes, when there are parameters here, overly long sentences will not occur.
