### ISSUE TITLE
请问为什么安装后无法打开呢？

### ISSUE THREAD

**Issue by latinisation** [CheshireCC/faster-whisper-GUI#113]
任务管理器里看了甚至没有启动的痕迹。也安装了ffmpeg，是不支持win11吗？

**Comment by latinisation** [comment]
福至心灵，“以管理员身份运行”已解决

**Comment by CheshireCC** [comment]
> 福至心灵，“以管理员身份运行”已解决

重新安装一下吧，你安装到需要管理员权限的硬盘上去了，管理员权限运行软件的话，可能会导致文件拖放功能失效，别的倒也没啥问题

**Comment by l1138583217** [comment]
版本	Windows 11 专业版
版本	23H2
安装日期	‎2024/‎1/‎9
操作系统版本	22631.3155
体验	Windows Feature Experience Pack 1000.22684.1000.0

管理员账号登录WIN，以管理员权限安装，以管理员权限运行 ，打不开~~日志在哪个路径啊

**Comment by l1138583217** [comment]
> 版本 Windows 11 专业版 版本 23H2 安装日期 ‎2024/‎1/‎9 操作系统版本 22631.3155 体验 Windows Feature Experience Pack 1000.22684.1000.0
> 
> 管理员账号登录WIN，以管理员权限安装，以管理员权限运行 ，打不开~~日志在哪个路径啊 @CheshireCC

解决了，卸载后把安装目录删干净

**Comment by CheshireCC** [comment]
> > 版本 Windows 11 专业版 版本 23H2 安装日期 ‎2024/‎1/‎9 操作系统版本 22631.3155 体验 Windows Feature Experience Pack 1000.22684.1000.0
> > 管理员账号登录WIN，以管理员权限安装，以管理员权限运行 ，打不开~~日志在哪个路径啊 @CheshireCC
> 
> 解决了，卸载后把安装目录删干净

cache 目录下可能有下载的模型缓存，temp 文件夹下可能有临时文件，可以不做清理，其余文件夹均可清理
日志文件是在安装目录的根目录下，和主程序同级别目录下
