### ISSUE TITLE
0.7.2 无论设置语言还是auto，最后结果都是英文

### ISSUE THREAD

**Issue by leominor46** [CheshireCC/faster-whisper-GUI#119]
语音是一段中文对话
音频语言无论指定zh或者auto，最后结果都是英文。

<img width="937" alt="Snipaste_2024-04-11_21-22-51" src="https://github.com/CheshireCC/faster-whisper-GUI/assets/57203372/43da5e91-ea9c-4778-9c5e-4d5be02d5c04">
<img width="830" alt="Snipaste_2024-04-11_21-23-12" src="https://github.com/CheshireCC/faster-whisper-GUI/assets/57203372/1b404d51-c866-46f6-9bd6-5201815db953">
使用auto检测为中文，但结果仍为英文
<img width="884" alt="Snipaste_2024-04-11_21-24-09" src="https://github.com/CheshireCC/faster-whisper-GUI/assets/57203372/d3d8a311-3089-42e2-90f8-35f365733d45">

**Comment by leominor46** [comment]
> 模型设置里面的翻译为英语是不是打开了

没有开的
<img width="1192" alt="Snipaste_2024-04-11_23-13-03" src="https://github.com/CheshireCC/faster-whisper-GUI/assets/57203372/cc63409c-7786-4855-8587-fe021ffebaa0">

开了以后会变成一半中文一般英文奇怪的样子
<img width="533" alt="Snipaste_2024-04-11_23-13-50" src="https://github.com/CheshireCC/faster-whisper-GUI/assets/57203372/4510d7cf-9bcc-4609-bced-6333b9349086">

**Comment by leominor46** [comment]
这个是日志，语言设置auto，翻译英语为关
``` 
==========2024-04-12_00:49:48==========
==========Process==========

redirect std output
vad_filter : True
    -threshold                : 0.5
    -min_speech_duration_ms   : 250
    -max_speech_duration_s    : inf
    -min_silence_duration_ms  : 2000
    -window_size_samples      : 1024
    -speech_pad_ms            : 400
Transcribes options:
    -audio : ['G:/用户/Videos/Nvidia/手机/XXX 2.m4a']
    -language : None
    -task : False
    -beam_size : 5
    -best_of : 5
    -patience : 1.0
    -length_penalty : 1.0
    -temperature : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    -compression_ratio_threshold : 2.4
    -log_prob_threshold : -1.0
    -no_speech_threshold : 0.6
    -condition_on_previous_text : False
    -initial_prompt : None
    -prefix : None
    -suppress_blank : True
    -suppress_tokens : [-1]
    -without_timestamps : False
    -max_initial_timestamp : 1.0
    -word_timestamps : False
    -prepend_punctuations : "'“¿([{-
    -append_punctuations : "'.。,，!！?？:：”)]}、
    -repetition_penalty : 1.0
    -no_repeat_ngram_size : 0
    -prompt_reset_on_temperature : 0.5
create transcribe process with 1 workers
start transcribe process
G:/用户/Videos/Nvidia/手机/XXX 2.m4a zh
convert to Simplified Chinese
len:28
len_segments_path_info_result: 1
Create Tables
addSubInterface:tab_G:/用户/Videos/Nvidia/手机/XXX 2.m4a
len_model: 1
```

下面是设置
<img width="884" alt="Snipaste_2024-04-12_00-53-56" src="https://github.com/CheshireCC/faster-whisper-GUI/assets/57203372/45d2b617-b911-46e4-bd01-d2e821e7dc5e">

**Comment by FreemanZ** [comment]
不清楚你用的是什么模型，一般Large V2、V3不至于出现这个问题，或者可以试试先在Demucs里把Vocal音轨抽出来减少干扰，可能原本音频里面有什么混响，然后到FasterWhisper设置里的初始提示词里输入 中文语音 再尝试一下。

**Comment by leominor46** [comment]
> 不清楚你用的是什么模型，一般Large V2、V3不至于出现这个问题，或者可以试试先在Demucs里把Vocal音轨抽出来减少干扰，可能原本音频里面有什么混响，然后到FasterWhisper设置里的初始提示词里输入 中文语音 再尝试一下。

模型就是在软件里面下的 large v3，我换了其他语言，出来的也还是英文。。。很怪

我录了个过程视频，参数都在里面，有时间您可以看下。
https://www.bilibili.com/video/BV1SM4m1S7Mf/

**Comment by CheshireCC** [comment]
请看 B 站

**Comment by CheshireCC** [comment]
请看 BiliBili

**Comment by CheshireCC** [comment]
太长时间没有响应的 issue，现在将关闭
