### ISSUE TITLE
0.7.6在转写过程中突然闪退

### ISSUE THREAD

**Issue by nita0318** [CheshireCC/faster-whisper-GUI#122]
cuda转写一个40分钟长的音频，格式wav，转写至音频700s的位置时软件会突然闪退（不一定是700s，反正无法转写完成），窗口和日志均无报错。
显卡显存6G，v2模型转写过程中占用约2.8G，v3模型占用约4G
模型试过“guillaumekln_faster_whisper_large_v2”和“Systran_faster_whisper_large_v3”，都有闪退情况。
选项“转写结束后自动跳转”设置为“从不”

将处理设备由“cuda”更改为“cpu”则不会闪退，可以正常转写完成并保存字幕文件。

转写失败日志：
[faster_whisper.log](https://github.com/CheshireCC/faster-whisper-GUI/files/15047764/faster_whisper.log)
[fasterwhispergui.log](https://github.com/CheshireCC/faster-whisper-GUI/files/15047765/fasterwhispergui.log)

转写成功日志：
[faster_whisper.log](https://github.com/CheshireCC/faster-whisper-GUI/files/15047942/faster_whisper.log)
[fasterwhispergui.log](https://github.com/CheshireCC/faster-whisper-GUI/files/15047943/fasterwhispergui.log)

部分设置截图：
![1](https://github.com/CheshireCC/faster-whisper-GUI/assets/49789145/b21d09e2-e627-4e75-a2dd-fcc5f67b9aaa)
![2](https://github.com/CheshireCC/faster-whisper-GUI/assets/49789145/0971591a-f925-4ccf-a788-46c1b9b74856)

**Comment by CheshireCC** [comment]
好的，我将进行相关测试

**Comment by ld0574** [comment]
同样碰到了+1

**Comment by CheshireCC** [comment]
我认为该问题应该属于偶发性问题，我转写更长音频文件并没有出现闪退
能否提供数据进行测试，以排除数据方面的问题？

**Comment by CheshireCC** [comment]
不如打开系统内存回退试一下，另外，我觉得CPU正常处理的话，您的显卡可能有恙了

**Comment by CheshireCC** [comment]
数据我会立即进行测试

**Comment by CheshireCC** [comment]
第二份数据损坏
