### ISSUE TITLE
集成字幕语音对齐功能

### ISSUE THREAD

**Issue by ipp9** [CheshireCC/faster-whisper-GUI#123]
大佬，我发现转写之后的字幕，断句很容易有问题。
https://github.com/readbeyond/aeneas
这个工具可以让音频和文字（字幕）对齐，一般我是手动再编辑字幕，每不同行字幕断行
我觉得你的软件可以集成这个功能。
更好的方式是 识别出来的文本 调用kimi等AI模型 让它加上标调符号后，根据 “.”号进行换行，接着再调动这个软件对齐时间轴

**Comment by CheshireCC** [comment]
时间戳对齐功能由 whisperX 提供

**Comment by ipp9** [comment]
> 时间戳对齐功能由 whisperX 提供

会不会是因为我上不了 hugging Face 所以whisperX用不了？ 我是没搞懂这个功能怎么用的

**Comment by CheshireCC** [comment]
> > 时间戳对齐功能由 whisperX 提供
> 
> 会不会是因为我上不了 hugging Face 所以whisperX用不了？ 我是没搞懂这个功能怎么用的

是的，需要科学上网才能正常使用 whisperX
