### ISSUE TITLE
TypeError: QProgressBar(parent: Optional[QWidget] = None): argument 1 has unexpected type 'MySplashScreen'

### ISSUE THREAD

**Issue by learn1st** [CheshireCC/faster-whisper-GUI#127]
请教下：
     在python ven 环境中运行.\FasterWhisperGUI.py 提示Traceback (most recent call last):
  File "E:\github\fastwhisper\faster-whisper-GUI\FasterWhisperGUI.py", line 55, in <module>
    pb = ProgressBar(splash)
  File "E:\github\fastwhisper\faster-whisper-GUI\fastwhispergui\lib\site-packages\qfluentwidgets\components\widgets\progress_bar.py", line 16, in __init__
    super().__init__(parent)
TypeError: QProgressBar(parent: Optional[QWidget] = None): argument 1 has unexpected type 'MySplashScreen'
不知是什么引起的？

**Comment by CheshireCC** [comment]
```
pip install PySide6-Fluent-Widgets==1.5.5
pip install PySide6==6.6.1
```
试一下
或者环境换成 conda 环境试一下

**Comment by learn1st** [comment]
会不会是因为没有独显的原因，没有torch,我试了分享的exe,也是没有反应

**Comment by CheshireCC** [comment]
看看日志文件

**Comment by CheshireCC** [comment]
独显不影响启动
