### ISSUE TITLE
希望添加对distill-large-v3模型的支持

### ISSUE THREAD

**Issue by 1353604736** [CheshireCC/faster-whisper-GUI#130]
希望添加对distill-large-v3模型的支持

**Comment by CheshireCC** [comment]
自行下载模型并进行加载是可行的
https://huggingface.co/Systran/faster-distil-whisper-large-v3/tree/main

在线模式的支持将于下一个版本更新

**Comment by a442509097** [comment]
@CheshireCC 这个模型是不是不支持中文, 我设置里已经设置了中文, 但出来的是英文

**Comment by CheshireCC** [comment]
> @CheshireCC 这个模型是不是不支持中文, 我设置里已经设置了中文, 但出来的是英文
distill 模型需要使用语料对模型进行重新精炼，所以该模型只支持输出英文，输出其他语言需要对应的专门训练，该模型社区很早就在招募志愿者参与其他语言的支持工作

**Comment by martjay** [comment]
![Snipaste_2024-08-23_16-13-38](https://github.com/user-attachments/assets/371ebac4-01bc-430a-8b69-0bedd877199a)

**Comment by CheshireCC** [comment]
> > 自行下载模型并进行加载是可行的 https://huggingface.co/Systran/faster-distil-whisper-large-v3/tree/main
> > 在线模式的支持将于下一个版本更新
> 
> 怎么使用啊 我真的一点都不知道啊，我自定义了模型目录，然后用在线模型加载？为什么不能做一个可以选择模型的选项呢？
> 
> ![Snipaste_2024-08-23_16-11-54](https://private-user-images.githubusercontent.com/44982189/360844817-41aabd7d-df84-4dff-95ce-e6288561abfc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDQwNTUsIm5iZiI6MTcyNDQwMzc1NSwicGF0aCI6Ii80NDk4MjE4OS8zNjA4NDQ4MTctNDFhYWJkN2QtZGY4NC00ZGZmLTk1Y2UtZTYyODg1NjFhYmZjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA5MDIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OTExYzJmNTVmODZiMjIwMGUzNTc0MWNkMzIyN2Y2MDZlOGU2NDc2YjY3ZTc3ZGE4ZTE1YmY1MmMwZjE2ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y-4C13G_S8WF-3Hc-3Gg3pgQ7U2o83F6XczlmXZnWEU)

在线加载模型和本地模型只能选一个，选中的时候另一个选项就会失效，你定义的模型目录是针对本地模型的，在线模型就是选择模型了

**Comment by martjay** [comment]
> > > 自行下载模型并进行加载是可行的 https://huggingface.co/Systran/faster-distil-whisper-large-v3/tree/main
> > > 在线模式的支持将于下一个版本更新
> > 
> > 
> > 怎么使用啊 我真的一点都不知道啊，我自定义了模型目录，然后用在线模型加载？为什么不能做一个可以选择模型的选项呢？
> > ![Snipaste_2024-08-23_16-11-54](https://private-user-images.githubusercontent.com/44982189/360844817-41aabd7d-df84-4dff-95ce-e6288561abfc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDQwNTUsIm5iZiI6MTcyNDQwMzc1NSwicGF0aCI6Ii80NDk4MjE4OS8zNjA4NDQ4MTctNDFhYWJkN2QtZGY4NC00ZGZmLTk1Y2UtZTYyODg1NjFhYmZjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA5MDIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OTExYzJmNTVmODZiMjIwMGUzNTc0MWNkMzIyN2Y2MDZlOGU2NDc2YjY3ZTc3ZGE4ZTE1YmY1MmMwZjE2ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y-4C13G_S8WF-3Hc-3Gg3pgQ7U2o83F6XczlmXZnWEU)
> 
> 在线加载模型和本地模型只能选一个，选中的时候另一个选项就会失效，你定义的模型目录是针对本地模型的，在线模型就是选择模型了

已经自己解决了，谢谢老大
