### ISSUE TITLE
使用"distil-large-v3"模型时遇到了仅输出英语的问题

### ISSUE THREAD

**Issue by FUmeCK** [CheshireCC/faster-whisper-GUI#135]
使用0.7.6版本,加载HuggingFace中提供的 "distil-large-v3" 模型文件,未打开'翻译为英语'功能,音频语言设置为 '简体中文' 时仍输出英文结果,仔细看了下,大概是翻译为英文后的结果,尝试重启应用,开关功能,重启电脑,重新载入模型,仍没有解决.
是我调整的问题吗?
日志:
"language:zh
Transcribes options:
    -audio : [文件.m4a']
    -language : zh
    -task : False
    -beam_size : 5
    -best_of : 5
    -patience : 1.0
    -length_penalty : 1.8
    -temperature : [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
    -compression_ratio_threshold : 2.4
    -log_prob_threshold : -1.0
    -no_speech_threshold : 0.6
    -condition_on_previous_text : False
    -initial_prompt : None
    -prefix : None
    -suppress_blank : True
    -suppress_tokens : [-1]
    -without_timestamps : True
    -max_initial_timestamp : 1.0
    -word_timestamps : False
    -prepend_punctuations : "'“¿([{-
    -append_punctuations : "'.。,，!！?？:：”)]}、
    -repetition_penalty : 1.0
    -no_repeat_ngram_size : 0
    -prompt_reset_on_temperature : 0.5
开始处理音频...
  Detected language [Chinese] with probability [100.00%]
  Audio duration     —— [00:08:29.2368] 
  after VAD duration —— [00:08:28.9968]"

**Comment by FUmeCK** [comment]
抱歉,没看ReadMe,这个模型只支持英文.

**Comment by fivenull** [comment]
> 抱歉,没看ReadMe,这个模型只支持英文.

请问一下，如果是输出中文的话用什么模型最好？
