### ISSUE TITLE
一般求助：safetensor的whisper模型怎么转换成这个项目能用的

### ISSUE THREAD

**Issue by A2Sumie** [CheshireCC/faster-whisper-GUI#138]
想用这个，https://huggingface.co/kotoba-tech/kotoba-whisper-v1.1
他的1.0有faster-whisper的但是时轴是不可用的状态

**Comment by CheshireCC** [comment]
16位
https://huggingface.co/CheshireCC/kotoba-whisper-v1.1-faster/tree/main

32位
https://huggingface.co/CheshireCC/kotoba-whisper-v1.1-faster-32bit/tree/main

**Comment by A2Sumie** [comment]
神！太感谢了
