### ISSUE TITLE
使用技巧问题请教

### ISSUE THREAD

**Issue by steamch** [CheshireCC/faster-whisper-GUI#143]
如何在本地模型的位置里手动切换模型？
还有一个为什么音频文件放进去会自动把中文翻译成英文
在转写参数里我已经设置了简体中文

**Comment by CheshireCC** [comment]
每个不同模型单独放一个文件夹，相关的文件也一起放进去，本地模型那里选择不同文件夹就是不同模型了
部分模型只支持英语输出 比如 后缀带 .en 的 还有 dulist 模型

**Comment by steamch** [comment]
> 每个不同模型单独放一个文件夹，相关的文件也一起放进去，本地模型那里选择不同文件夹就是不同模型了 部分模型只支持英语输出 比如 后缀带 .en 的 还有 dulist 模型

谢谢。确实可以了。但是很奇怪的一个点是当我使用软件自带的下载功能下载largev3模型，他还是自动翻译成英文。唯独当我手动下载替换后才会正确显示我指定的中文
