### ISSUE TITLE
请问该如何编译成可执行文件呢

### ISSUE THREAD

**Issue by anningning** [CheshireCC/faster-whisper-GUI#145]
大佬请帮忙告知如何编译成exe    自行编译了多次都不符合预期

**Comment by YuseiwithJackandCrow** [comment]
不用编译啊，这里下载就行，作者有编译好的版本

**Comment by CheshireCC** [comment]
> 大佬请帮忙告知如何编译成exe 自行编译了多次都不符合预期

python 编译本身是个伪命题，流行方法主要是 pytinstaller 和 Nuitka 两种，我的发布版本采用 Nuitka 进行编译，然后自行制作安装包。
Nuitka 本身坑就挺多的，复杂程序编译的时候由于某些外部引入包本身的原因，可能需要对特定包的代码进行修改，参数使用也有讲究，需要长期摸索。
