### ISSUE TITLE
转录时出现单字输出的问题

### ISSUE THREAD

**Issue by sonyjams** [CheshireCC/faster-whisper-GUI#153]
![Screenshot 2024-06-12 181237](https://github.com/CheshireCC/faster-whisper-GUI/assets/58423306/281dcb98-e254-4567-8ca5-bc3535228f47)
VAD的最小静息时长无论是默认还是1000结果都相同，关闭VAD也会出现该情况，其余参数未变动

**Comment by nnnnn376** [comment]
你把单词级时间戳打开，然后再用whisperX时间戳对齐试试，可能有所好转

**Comment by nnnnn376** [comment]
你可以把最小静息时长调成100，好像调大了字幕更碎

**Comment by sonyjams** [comment]
> 你可以把最小静息时长调成100，好像调大了字幕更碎

这些都调过了，不管用，最后卸载重装解决了

**Comment by sonyjams** [comment]
![屏幕截图 2024-06-17 120202](https://github.com/CheshireCC/faster-whisper-GUI/assets/58423306/f8e7eb00-8136-4464-a70c-bbc9d81619b6)
阴差阳错下发现是这个之前调成了1导致的

**Comment by nnnnn376** [comment]
> ![屏幕截图 2024-06-17 120202](https://private-user-images.githubusercontent.com/58423306/340174251-f8e7eb00-8136-4464-a70c-bbc9d81619b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTk0MjMsIm5iZiI6MTcxODYxOTEyMywicGF0aCI6Ii81ODQyMzMwNi8zNDAxNzQyNTEtZjhlN2ViMDAtODEzNi00NDY0LWE3MGMtYmJjOWQ4MTYxOWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEwMTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMDM0OGE4NjNmMDgxNWI1N2I3Y2ViODAwNGVjOGUxM2VlMmVlOTIyNzcxOTRiYmExYWYyOTczMDUwZDQ2MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NiqaK2EMTuRaOKUBRjOISaFOZ9x_uIHXFZZlObBiR3s) 阴差阳错下发现是这个之前调成了1导致的

是的，这个调成1的话，如果两句话的开头词语是相同的就会出现这种错误

**Comment by CheshireCC** [comment]
> > ![屏幕截图 2024-06-17 120202](https://private-user-images.githubusercontent.com/58423306/340174251-f8e7eb00-8136-4464-a70c-bbc9d81619b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTk0MjMsIm5iZiI6MTcxODYxOTEyMywicGF0aCI6Ii81ODQyMzMwNi8zNDAxNzQyNTEtZjhlN2ViMDAtODEzNi00NDY0LWE3MGMtYmJjOWQ4MTYxOWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEwMTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMDM0OGE4NjNmMDgxNWI1N2I3Y2ViODAwNGVjOGUxM2VlMmVlOTIyNzcxOTRiYmExYWYyOTczMDUwZDQ2MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NiqaK2EMTuRaOKUBRjOISaFOZ9x_uIHXFZZlObBiR3s) 阴差阳错下发现是这个之前调成了1导致的
> 
> 是的，这个调成1的话，如果两句话的开头词语是相同的就会出现这种错误



> > ![屏幕截图 2024-06-17 120202](https://private-user-images.githubusercontent.com/58423306/340174251-f8e7eb00-8136-4464-a70c-bbc9d81619b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTk0MjMsIm5iZiI6MTcxODYxOTEyMywicGF0aCI6Ii81ODQyMzMwNi8zNDAxNzQyNTEtZjhlN2ViMDAtODEzNi00NDY0LWE3MGMtYmJjOWQ4MTYxOWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEwMTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMDM0OGE4NjNmMDgxNWI1N2I3Y2ViODAwNGVjOGUxM2VlMmVlOTIyNzcxOTRiYmExYWYyOTczMDUwZDQ2MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NiqaK2EMTuRaOKUBRjOISaFOZ9x_uIHXFZZlObBiR3s) 阴差阳错下发现是这个之前调成了1导致的
> 
> 是的，这个调成1的话，如果两句话的开头词语是相同的就会出现这种错误

😲😲😲😲 厉害了，这个参数是用来防止 重复 token 输出的，主要是用来抑制空白部分的幻听复读现象。。没想到会造成 whisperX 的识别问题

**Comment by CheshireCC** [comment]
> > ![屏幕截图 2024-06-17 120202](https://private-user-images.githubusercontent.com/58423306/340174251-f8e7eb00-8136-4464-a70c-bbc9d81619b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTk0MjMsIm5iZiI6MTcxODYxOTEyMywicGF0aCI6Ii81ODQyMzMwNi8zNDAxNzQyNTEtZjhlN2ViMDAtODEzNi00NDY0LWE3MGMtYmJjOWQ4MTYxOWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEwMTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMDM0OGE4NjNmMDgxNWI1N2I3Y2ViODAwNGVjOGUxM2VlMmVlOTIyNzcxOTRiYmExYWYyOTczMDUwZDQ2MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NiqaK2EMTuRaOKUBRjOISaFOZ9x_uIHXFZZlObBiR3s) 阴差阳错下发现是这个之前调成了1导致的
> 
> 是的，这个调成1的话，如果两句话的开头词语是相同的就会出现这种错误



> > ![屏幕截图 2024-06-17 120202](https://private-user-images.githubusercontent.com/58423306/340174251-f8e7eb00-8136-4464-a70c-bbc9d81619b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTk0MjMsIm5iZiI6MTcxODYxOTEyMywicGF0aCI6Ii81ODQyMzMwNi8zNDAxNzQyNTEtZjhlN2ViMDAtODEzNi00NDY0LWE3MGMtYmJjOWQ4MTYxOWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEwMTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMDM0OGE4NjNmMDgxNWI1N2I3Y2ViODAwNGVjOGUxM2VlMmVlOTIyNzcxOTRiYmExYWYyOTczMDUwZDQ2MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NiqaK2EMTuRaOKUBRjOISaFOZ9x_uIHXFZZlObBiR3s) 阴差阳错下发现是这个之前调成了1导致的
> 
> 是的，这个调成1的话，如果两句话的开头词语是相同的就会出现这种错误

😲😲😲😲 厉害了，这个参数是用来防止 重复 token 输出的，主要是用来抑制空白部分的幻听复读现象。。没想到会造成识别问题
