### ISSUE TITLE
感觉有个bug是如果先加载模型，再修改设置，设置就不生效了

### ISSUE THREAD

**Issue by RoachLin** [CheshireCC/faster-whisper-GUI#156]
感觉有个bug是必须在加载模型设置好所有参数，最后再加载模型，再添加音频文件启动，
如果是先加载模型，再修改设置，设置就不生效了，
比如我先设置的用cuda，然后加载模型，再改为用cpu，这时还是会用cuda

**Comment by CheshireCC** [comment]
加载模型都加载到显存里去了，还怎么用 CPU 跑？

**Comment by RoachLin** [comment]
噢那我理解错了

**Comment by CheshireCC** [comment]
> 噢那我理解错了

修改参数主要还是针对转写设置
