### ISSUE TITLE
希望能开放这些参数的调节

### ISSUE THREAD

**Issue by nnnnn376** [CheshireCC/faster-whisper-GUI#157]
max_length:             448
num_samples_per_token:  320
time_precision:  0.02
tokens_per_second:  50
input_stride:  2

这几个参数似乎只能在日志上看到，在界面中没有看到能调的地方，而且我认为和whisperX时间戳对齐失败可能有些关系，如果能采纳，无比感谢

**Comment by nnnnn376** [comment]
[Uploading 对齐失败日志.txt…]()

**Comment by nnnnn376** [comment]
[对齐失败日志.txt](https://github.com/user-attachments/files/15841182/default.txt)

**Comment by CheshireCC** [comment]
> [对齐失败日志.txt](https://github.com/user-attachments/files/15841182/default.txt)

当字幕中有大量 短促对话甚至时间戳紧密相连或者相互压盖的情况下，具体体现为 一个人说话的时候被另一个人快速打断，从字母上看就是有很多内容很短、持续时间很短但密集的字幕语句的时候就会出现该错误，
暂时的解决方案，你可以在字幕表格中合并掉内容太短或者持续时间太短的字幕

**Comment by CheshireCC** [comment]
> max_length: 448 num_samples_per_token: 320 time_precision: 0.02 tokens_per_second: 50 input_stride: 2
> 
> 这几个参数似乎只能在日志上看到，在界面中没有看到能调的地方，而且我认为和whisperX时间戳对齐失败可能有些关系，如果能采纳，无比感谢

目前 fw 后端还只能调整 max_length 参数，在转写参数页面，该参数为最大新令牌数
