### ISSUE TITLE
0.030版本发现一个BUG

### ISSUE THREAD

**Issue by wode556601** [CheshireCC/faster-whisper-GUI#17]
在听写完成后如果我直接点“保存字幕文件”会正常生成字幕文件，但是我如果点击了“whisperX 时间轴对齐”后，在点击“保存字幕文件”会无法生成字幕文件

**Comment by CheshireCC** [comment]
时间戳对齐功能需要下载模型支持，国内网络不好需要 使用 VPN ，
另外不是所有的语言都被支持，需要有对应预训练模型的语言才能运行该功能
