### ISSUE TITLE
AMAZING PROJECT

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [CheshireCC/faster-whisper-GUI#18]
HELLO MAN...CONGRATULATIONS FOR YOUR AMAZING PROJECT!!!BUT COULD YOU PLEASE TELL ME STEP BY STEP WHAT I HAVE TO DO FOR USE YOUR AMAZING PROJECT?I AM NEW ON THIS AND I DONT KNOW!!!

**Comment by CheshireCC** [comment]
1. you need to download models from [huggingface](https://huggingface.co/models?sort=trending&search=faster-whisper) ,and put all files in the same folder, just like `model.bin`、`config.json` and so on,
2. go to `Model` page, select model folder, and load model.
3. go to `Transciption` page, select audio or video files that you need to get subtitles, clicke `Start`  button to get subtitles
4. in `output` page，you can try to edit or save subtitls files.
