### ISSUE TITLE
如何在Linux上安装 - how to install on linux

### ISSUE THREAD

**Issue by amrmenam** [CheshireCC/faster-whisper-GUI#180]
我尝试在 Ubuntu 上安装该程序，但失败了。有关于如何安装的说明吗？- I tried to install the program on Ubuntu but I couldn't. Is there an explanation of how to install?

**Comment by CheshireCC** [comment]
exe 可执行程序只能在 Windows10 及以上的系统中安装
Ubuntu 系统要运行本程序可以提尝试使用源代码进行修改调试，由于 程序主体依赖于 PySide6（Qt 的 python API ），而 Qt 本身是跨平台的，所以修改的难度可能不会太大，如果不了解程序设计的相关知识，那么可以先等，我后续可能会针对 Ubuntu 发布相应分支
