### ISSUE TITLE
faster-whisper 1.0.3

### ISSUE THREAD

**Issue by 188198** [CheshireCC/faster-whisper-GUI#184]
大佬您好，请问最近有更新计划么。faster whisper1.0.3了，vad版本重大升级了，效果应该提升不小。

Upgrade Silero-Vad model to latest V5 version (https://github.com/SYSTRAN/faster-whisper/pull/884)
Silero-vad V5 release: https://github.com/snakers4/silero-vad/releases/tag/v5.0

window_size_samples parameter is fixed at 512.
Change to use the state variable instead of the existing h and c variables.
Slightly changed internal logic, now some context (part of previous chunk) is passed along with the current chunk.
Change the dimensions of the state variable from 64 to 128.
Replace ONNX file with V5 version
Other changes
Improve language detection when using clip_timestamps (https://github.com/SYSTRAN/faster-whisper/pull/867)
Docker file improvements (https://github.com/SYSTRAN/faster-whisper/pull/848)
Fix https://github.com/SYSTRAN/faster-whisper/issues/839 incorrect clip_timestamps being used in model (https://github.com/SYSTRAN/faster-whisper/pull/842)

**Comment by CheshireCC** [comment]
正在计划更新
