### ISSUE TITLE
multiple speaks seperation failure

### ISSUE THREAD

**Issue by flottant** [CheshireCC/faster-whisper-GUI#19]
log below:
```
==========2023-10-28_19:44:46==========
==========Speaker_Diarize==========


Speaker diarize and alignment
load speaker brain model...

Could not download 'pyannote/speaker-diarization' pipeline.
It might be because the pipeline is private or gated so make
sure to authenticate. Visit https://hf.co/settings/tokens to
create your access token and retry with:

   >>> Pipeline.from_pretrained('pyannote/speaker-diarization',
   ...                          use_auth_token=YOUR_AUTH_TOKEN)

If this still does not work, it might be because the pipeline is gated:
visit https://hf.co/pyannote/speaker-diarization to accept the user conditions.
speaker diarize...
failed to diarize speaker!
Error: 'NoneType' object is not callable
UPdata DataModel
```
After change the auth_token to my own accessible token, but still seems unavailable.

**Comment by CheshireCC** [comment]
you need to visit `https://hf.co/pyannote/speaker-diarization` to finish the questionnaire survey firstly.
Then generate a new user token.

**Comment by flottant** [comment]
> you need to visit `https://hf.co/pyannote/speaker-diarization` to finish the questionnaire survey firstly.
> Then generate a new user token. 

I have tried to change into my own token, which is accessible in whisperX command line mode. However it still cannot work in gui.
I will try again later.

**Comment by flottant** [comment]
I have regenerated the token and it works. Thanks a lot.
It seems that when it is the first time to run the diarization function, you should press the "diarization" button first then press the " timestamp alignment" button, otherwise it may occour problems.
I am not sure whether it's a common condition.

<img width="638" alt="order" src="https://github.com/CheshireCC/faster-whisper-GUI/assets/53401195/376617e1-c457-4bf7-9ef8-0054b24588f7">
