### ISSUE TITLE
用不了GPU

### ISSUE THREAD

**Issue by vince-H15** [CheshireCC/faster-whisper-GUI#193]
设备号选0就可以加载模型，但是选1不行，无论是在线模型还是本地的，这是怎么回事？
![297fd6824633360e8423da01fdd59a0](https://github.com/user-attachments/assets/98b16b6b-bf7a-4bcf-a44c-42eb5491fc2d)
![6289a99a0ea41a17b0876604402259e](https://github.com/user-attachments/assets/64323a89-db30-43c7-af54-9d5957ed972f)

**Comment by vince-H15** [comment]
![image](https://github.com/user-attachments/assets/1324dd05-341d-4f5a-b7e2-8ad428c562a3)
电脑是有GPU的。

**Comment by CheshireCC** [comment]
设备号默认是0 那是你的第一块独显，除非你有多块 GPU 设备，否则不能选其他值

**Comment by vince-H15** [comment]
那选了0，GPU利用率低呢，基本没调用

**Comment by CheshireCC** [comment]
> 那选了0，GPU利用率低呢，基本没调用

windows 操作系统 设置 里面，有GPU 相关选项，设置一下
