### ISSUE TITLE
关于生成字幕文件格式问题

### ISSUE THREAD

**Issue by nzky0** [CheshireCC/faster-whisper-GUI#20]
你好，使用这个软件可以批量非常方便，然后结合PROMT 这款离线翻译软件进行英转中文，制作双语字幕，但是在准备翻译生成的srt文件时，PROMT却提示格式不支持，又分别测试了VTT，LRC都提示不支持，但是之前我翻译同样的音频，使用whisperDesktop生成的srt文件却没有这个问题，然而whisperDesktop却不能批量转，这个有点头疼了，想请忙看看问题出在哪里了？？？

**Comment by CheshireCC** [comment]
你好，能介绍一下你的翻译方案吗？我不知道你使用什么样的翻译软件，如果有可能请提供该方案的部署方法

**Comment by nzky0** [comment]
> 你好，可以介紹一下你的翻譯方案嗎？ 我不知道你使用什麼樣的翻譯軟體，如果有可能請提供該方案的部署方法

啊，谢谢回复，我的方法不是什么高级的方法，就是先使用大佬的这个GUI工具将英文教程转写后保存为srt字幕文件，然后再使用PROMT master这个离线翻译工具，这个工具是从网上下载的PJ版，然后将srt文件导进去就能翻译为中文了，只能保存为txt文件，我再用bat批处理将翻译的txt中的中文内容合并到转写的英文srt文件中，就成双语字幕了，应为网络问题，选择这种离线的方法，比较笨的，现在就是苦于转写后的srt文件竟然不被支持

**Comment by CheshireCC** [comment]
格式问题在古早时期曾经被提出来过，但是目前我对比了 WhisperDesktop 软件输出的 srt 格式字幕，除了编码比太一样，其余格式基本一致，如果你愿意尝试，可以试试：
使用 Notepad++，打开转写后的 srt 文件，在编码菜单中选择 “使用 UTF-8 BOM 编码” 来转换字幕编码，然后另存字幕文件即可
再尝试使用转换过编码的字幕文件进行翻译
如果不能正常读取的话，请提供翻译软件的部署方案（百度云 is also ok），由我来完成测试并进行排查

**Comment by nzky0** [comment]
> 格式问题在古早时期曾经被提出来过，但是目前我对比了 WhisperDesktop 软件输出的 srt 格式字幕，除了编码比太一样，其余格式基本一致，如果你愿意尝试，可以试试： 使用 Notepad++，打开转写后的 srt 文件，在编码菜单中选择 “使用 UTF-8 BOM 编码” 来转换字幕编码，然后另存字幕文件即可 再尝试使用转换过编码的字幕文件进行翻译 如果不能正常读取的话，请提供翻译软件的部署方案（百度云 is also ok），由我来完成测试并进行排查

正如你所说的这种方法我测试了是有效的，谢谢，不过如果文件多的话会有点麻烦了

**Comment by CheshireCC** [comment]
我采用了通用编码 UTF8 但只考虑音视频文件播放和显示，对于此种情况应当由翻译软件作者提供对通用 UTF-8 编码的支持，
另外你可以采用一些批量方式转换文件编码到 utf8-BOM

**Comment by CheshireCC** [comment]
0.4.3 版本已支持设置 srt 格式字幕文件的输出编码，但仅限 srt 格式生效
