### ISSUE TITLE
WhisperX对齐后无法保存某个文件的字幕

### ISSUE THREAD

**Issue by A2Sumie** [CheshireCC/faster-whisper-GUI#202]
带点版权我不知道怎么传，在我的环境上某个特定文件点击Save to File后并不会保存字幕，事先运行了一下whisper x对齐
方才试了一下，如果不运行WhisperX就可以保存
以防万一是已经重启过程序的
MediaInfo

概览
特征 ID                          : 186940460791298102658806019952928453021 (0x8CA36C51F4C3379A961E898CA4F5719D)
完整名称                           : E:\Downloads\uisk1annL.mkv
格式                             : Matroska
格式版本                           : Version 4
文件大小                           : 2.34 GiB
时长                             : 1 时 15 分
总体码率                           : 4 428 kb/s
帧率                             : 30.000 FPS
编码日期                           : 2024-08-09 12:23:51 UTC
编码程序                           : mkvmerge v86.0 ('Winter') 64-bit
编码函数库                          : libebml v1.4.5 + libmatroska v1.7.1

视频
ID                             : 1
格式                             : AVC
格式/信息                          : Advanced Video Codec
格式配置 (Profile)                 : High@L4
格式设置                           : CABAC / 3 Ref Frames
格式设置, CABAC                    : 是
格式设置, 参考帧                      : 3 帧
格式设置, GOP                      : M=1, N=30
编解码器 ID                        : V_MPEG4/ISO/AVC
时长                             : 1 时 15 分
码率模式                           : 恒定码率 (CBR)
码率                             : 4 300 kb/s
宽度                             : 1 920 像素
高度                             : 1 080 像素
画面比例                           : 16:9
帧率模式                           : 恒定帧率 (CFR)
帧率                             : 30.000 FPS
色彩空间                           : YUV
色度抽样                           : 4:2:0
位深                             : 8 位
扫描类型                           : 逐行扫描 (连续)
数据密度 [码率/(像素*帧率)]              : 0.069
流大小                            : 2.28 GiB (97%)
Default                        : 是
Forced                         : 否

音频
ID                             : 2
格式                             : AAC LC
格式/信息                          : Advanced Audio Codec Low Complexity
编解码器 ID                        : A_AAC-2
时长                             : 1 时 15 分
码率                             : 126 kb/s
声道数                            : 2 声道
声道布局                           : L R
采样率                            : 44.1 kHz
帧率                             : 43.066 FPS (1024 SPF)
压缩模式                           : 有损
相对视频的延迟                        : -36 毫秒
流大小                            : 68.1 MiB (3%)
语言                             : 英语 (English)
Default                        : 是
Forced                         : 否

**Comment by A2Sumie** [comment]
再行WhisperX后可以保存了，可能是抽风

**Comment by CheshireCC** [comment]
对齐失败的话字幕会丢失导致不能保存

**Comment by gsxgmpkt9020** [comment]
一般执行whisperX其他功能前要先保存字幕文件以防万一
