### ISSUE TITLE
执行转写未完成点击“取消”，之后再添加文件点击“开始”也只会提示 是否取消操作

### ISSUE THREAD

**Issue by myholiday** [CheshireCC/faster-whisper-GUI#207]
![image](https://github.com/user-attachments/assets/3ba906b3-9051-4321-8098-679ffc19af2f)

**Comment by CheshireCC** [comment]
取消这个东西因为一些原因，并不能立即结束全部进程，所以可能需要过一会儿之后，全部进程才会退出，然后才能开始下一个工作
