### ISSUE TITLE
工作异常

### ISSUE THREAD

**Issue by choiree** [CheshireCC/faster-whisper-GUI#208]
你好 ，翻译不工作是为什么，本来以为是模型选大了，换base还是不行，
<img width="931" alt="屏幕截图 2024-08-16 161749" src="https://github.com/user-attachments/assets/e33b989b-b298-47b0-be3b-50cf1664fc9e">

**Comment by CheshireCC** [comment]
转录失败的时候，左下角设置，检查下日志

**Comment by choiree** [comment]
错误代码是这个，RuntimeError: parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

**Comment by choiree** [comment]
貌似是要用老版本的 ctranslate2.dll，我的显卡太老了

**Comment by CheshireCC** [comment]
> 貌似是要用老版本的 ctranslate2.dll，我的显卡太老了

现在 ctranslate2 确实只支持 CUDA12 了。
