### ISSUE TITLE
faster-whisper-GUI  0.4.0，转换效率很慢

### ISSUE THREAD

**Issue by jy3344511** [CheshireCC/faster-whisper-GUI#21]
使用同样的模型faster-whisper-large-v2，转换同样时长的音频，用faster-whisper-GUI  0.4.0的话，要1、2个小时，才能转完。

出了字幕以后，因为还要调整，所以需要用到Subtitle Edit。结果发现Subtitle Edit里有一个叫Purfview's Whisper Faster的引擎，于是把模型faster-whisper-large-v2复制到Subtitle Edit指定的目录下使用，还是转换同样时长的音频，结果只用了几分钟，就转完了。

两个软件，在转换的过程中，GPU的实际使用率都在90-100%之间浮动，但转换的时间差别太大，不知道是什么问题。

**Comment by CheshireCC** [comment]
为了照顾小显存的朋友（尤其是有批量转写需求的），我在代码中频繁使用了 gc 和内存、显存清理，这可能会拖慢一部分转写效率，但仅仅只是可能原因的一种，因为照顾线程的取消等操作进行的线程检查也有可能造成部分性能问题。如果你想更快速的执行转写工作，可以尝试：
1. 无论使用哪种模型，都使用 int8 作为 `计算精度`，这应该能够较大程度提升转写效率，同时这对转写精度有一定影响，但我认为对于人声清晰、质量较好的音频影响微乎其微。使用 int8 作为计算精度同时也能大幅度降低对显卡显存、内存、显卡计算能力的占用和需求，大约只需要 3GB 显存、原本的 70% 的CUDA计算能力就可以运行转写。
2. 将温度选项也就是 `采样热度候选` 设置为一个 `0`，这可能加速一点点转写速度，同时可能解决部分闪退问题。但同时这也将会使温度回退配置失效，如果模型出现幻听、失败循环（重复同一句话或者无意义语句）请设置 `循环提示`为 `False` 。
3. 将 `分块大小` 设置 为 `1`, 实际测试中这确实加速了模型的提取速度，但是有测试认为 分块大小影响模型转写结果，但也有一些相关测试（就是你所说的 Purfview Faster Whisper）认为该值对转写结果影响不大，实际测试中该值越大就越占用计算资源和显存，该值调小之后确实加快了转写速度，但结合 faster-whisper官方说法该值越大可能转写效果就会越好。目前我个人尚未看出对结果的明显影响。
4. 过去本项目使用 cuda118 作为 CUDA 引擎，彼时转写效率确实高于现在，同时由于 torch 等相关套件进行了字节码编译的原因，运行速度也高于现在的版本，但是由于兼容 wshiperX 引擎的原因，我不得不放弃对 CT2 引擎所进行的兼容修改，重新使用 cuda117 引擎，而 torch 的 GPU 版本再编译已经无法完成而且价值不大，所以放弃了对 torch 及相关其他套件的编译工作，目前该部分程序工作在 python 环境下，但我并不清除这是否与性能瓶颈有关。

关于软件运行过程中的 显卡 GPU 使用率，如果使用 CUDA 引擎，则 CUDA 将会自动完成资源调度，无法干涉。对比 whisperDesktop 软件，其使用 whisper.cpp 后端，不使用 CUDA 引擎，而是使用 Direct 3D 着色渲染器来作为计算器，程序将自行控制资源调度和开销，这样其 GPU 占用始终能维持在接近 100%，但并不一定比使用 CUDA 核心效率更高。不过其作为一个尝试性项目，证明了即使不依赖 英伟达 CUDA 套件也有可能在支持更多设备、更多品牌硬件、更多显卡和CPU型号的基础之上运行深度学习项目。
关于软件转写效率以及目前仍然存在的运行稳定性问题我还将进一步进行的排查。

**Comment by jy3344511** [comment]
> 为了照顾小显存的朋友（尤其是有批量转写需求的），我在代码中频繁使用了 gc 和内存、显存清理，这可能会拖慢一部分转写效率，但仅仅只是可能原因的一种，因为照顾线程的取消等操作进行的线程检查也有可能造成部分性能问题。如果你想更快速的执行转写工作，可以尝试：
> 
> 1. 无论使用哪种模型，都使用 int8 作为 `计算精度`，这应该能够较大程度提升转写效率，同时这对转写精度有一定影响，但我认为对于人声清晰、质量较好的音频影响微乎其微。使用 int8 作为计算精度同时也能大幅度降低对显卡显存、内存、显卡计算能力的占用和需求，大约只需要 3GB 显存、原本的 70% 的CUDA计算能力就可以运行转写。
> 2. 将温度选项也就是 `采样热度候选` 设置为一个 `0`，这可能加速一点点转写速度，同时可能解决部分闪退问题。但同时这也将会使温度回退配置失效，如果模型出现幻听、失败循环（重复同一句话或者无意义语句）请设置 `循环提示`为 `False` 。
> 3. 将 `分块大小` 设置 为 `1`, 实际测试中这确实加速了模型的提取速度，但是有测试认为 分块大小影响模型转写结果，但也有一些相关测试（就是你所说的 Purfview Faster Whisper）认为该值对转写结果影响不大，实际测试中该值越大就越占用计算资源和显存，该值调小之后确实加快了转写速度，但结合 faster-whisper官方说法该值越大可能转写效果就会越好。目前我个人尚未看出对结果的明显影响。
> 4. 过去本项目使用 cuda118 作为 CUDA 引擎，彼时转写效率确实高于现在，同时由于 torch 等相关套件进行了字节码编译的原因，运行速度也高于现在的版本，但是由于兼容 wshiperX 引擎的原因，我不得不放弃对 CT2 引擎所进行的兼容修改，重新使用 cuda117 引擎，而 torch 的 GPU 版本再编译已经无法完成而且价值不大，所以放弃了对 torch 及相关其他套件的编译工作，目前该部分程序工作在 python 环境下，但我并不清除这是否与性能瓶颈有关。
> 
> 关于软件运行过程中的 显卡 GPU 使用率，如果使用 CUDA 引擎，则 CUDA 将会自动完成资源调度，无法干涉。对比 whisperDesktop 软件，其使用 whisper.cpp 后端，不使用 CUDA 引擎，而是使用 Direct 3D 着色渲染器来作为计算器，程序将自行控制资源调度和开销，这样其 GPU 占用始终能维持在接近 100%，但并不一定比使用 CUDA 核心效率更高。不过其作为一个尝试性项目，证明了即使不依赖 英伟达 CUDA 套件也有可能在支持更多设备、更多品牌硬件、更多显卡和CPU型号的基础之上运行深度学习项目。 关于软件转写效率以及目前仍然存在的运行稳定性问题我还将进一步进行的排查。

如果使用下载的本地模型的话，上述的一些参数更改后有效吗？
