### ISSUE TITLE
能准确控制断句吗？

### ISSUE THREAD

**Issue by martjay** [CheshireCC/faster-whisper-GUI#214]
比如说一行字幕多少个标点符号这样分，我感觉识别出来的字幕有的长有的短，如果不是整句的话，翻译起来很麻烦吧

**Comment by martjay** [comment]
![Snipaste_2024-08-31_22-58-34](https://github.com/user-attachments/assets/1a652ccd-d044-4e1b-b3ce-138f81465651)

**Comment by CheshireCC** [comment]
有手动分割选项可用，但是该功能测试很少，使用之后 VAD 将会失效

**Comment by martjay** [comment]
> 有手动分割选项可用，但是该功能测试很少，使用之后 VAD 将会失效

videotrans就能准确对每个断句分割，希望能优化啊，真的很头疼

**Comment by martjay** [comment]
> 有手动分割选项可用，但是该功能测试很少，使用之后 VAD 将会失效

还有另外一个实用功能没有实现，distil识别速度很快，我觉得完全可以做实时语音识别+字幕翻译，deeplx项目也能免费使用deepl，google也行，百度，腾讯，阿里
