### ISSUE TITLE
在whisperx后处理，如果使用了时间戳对齐或者分离说话人功能，保存字幕文件保存不了。

### ISSUE THREAD

**Issue by lizhendaccie** [CheshireCC/faster-whisper-GUI#215]
在whisperx后处理，如果使用了时间戳对齐或者分离说话人功能，保存字幕文件保存不了。
After post-processing in WhisperX, if timestamp alignment or speaker separation is used, the subtitle file cannot be saved.

你会发现点击了保存字幕文件，显示保存成功，但实际上字幕文件还在Temp目录里面，而且时间戳对齐功能点击后显示执行成功，实际上Temp文件夹里面那个字幕文件是没有任何变化的。
You will find that after clicking to save the subtitle file, it shows that the save was successful, but in fact, the subtitle file is still in the Temp folder. Moreover, after clicking the timestamp alignment function, it shows that the execution was successful, but in reality, there are no changes to the subtitle file in the Temp folder.

**Comment by CheshireCC** [comment]
使用 whisperX 需要下载、验证模型，需要科学上网手段

**Comment by lizhendaccie** [comment]
我有科学上网手段，但是在海外的电脑上面，怎么完成下载、验证模型到墙内的本地？我意思是怎么手动安装这个whisperX？

**Comment by kawae0709** [comment]
我之前也遇到了这个问题,就是whisperX都没有正确运行起来,参考
You may also need to install ffmpeg, rust etc. Follow openAI instructions here https://github.com/openai/whisper#setup.
安装后正常了

**Comment by CheshireCC** [comment]
ffmpeg 是必须的
