### ISSUE TITLE
Win10系统无法安装

### ISSUE THREAD

**Issue by EvthPst** [CheshireCC/faster-whisper-GUI#216]
下载了FasterWhisperGUI-0.8.0_installer.exe，点击安装文件，只能看见鼠标上的圈在转，然后就没有任何反应了，管理员模式运行也不行，任务管理器里没有任何进程。在另一台性能更好的Win11上一切正常。安装这个软件是否需要什么前置条件？对于显卡CPU有什么要求吗？

**Comment by CheshireCC** [comment]
只是安装的话，没什么特殊要求。。。。

**Comment by CheshireCC** [comment]
> 虽然找到了原因，但是这是为什么？

微软特色
