### ISSUE TITLE
请问识别结果怎么设置成简体中文？

### ISSUE THREAD

**Issue by moki-noob** [CheshireCC/faster-whisper-GUI#217]
识别了一段中文音频，精确度倒是没多大问题，但识别出的文字全是繁体，请问大佬们怎么解决呢
模型我用的是whisper-large-v3

**Comment by CheshireCC** [comment]
参数——语言——zhs-Simplified Chinese

**Comment by zlfengshare** [comment]
> 0.81版本，zhs-Simplified Chinese 设置了，还是繁体

音频是粤语，之前会自动识别为简体，卸载后升级版本就是繁体的，降级到原来的版本发现也是繁体，好奇怪

**Comment by CheshireCC** [comment]
只有繁体中文能稳定翻译成简体中文，但是粤语的话不一定能行
