### ISSUE TITLE
处理完成后自动关机

### ISSUE THREAD

**Issue by zuiaiyutu** [CheshireCC/faster-whisper-GUI#218]
希望增加一个处理完成后自动关机，就可以晚上开着电脑，转换，弄完了，就可以自动关机。
还有转换完成后，如果不需要whisperX的后处理，可以直接自动保存字幕到视频的文件夹，这样就不需要手动去点那个“保存字幕文件的按钮”

**Comment by CheshireCC** [comment]
之后再考虑吧，最近都太忙，7.29号新版本就做好了，没时间封包，到现在都没发😂😂😂😂

**Comment by zuiaiyutu** [comment]
> 之后再考虑吧，最近都太忙，7.29号新版本就做好了，没时间封包，到现在都没发😂😂😂😂

坐等更新
