### ISSUE TITLE
源码中include了错误的包

### ISSUE THREAD

**Issue by LtpLGM** [CheshireCC/faster-whisper-GUI#219]
Traceback (most recent call last):
  File "D:\faster-whisper-GUI-main\FasterWhisperGUI.py", line 93, in <module>
    from faster_whisper_GUI.mainWindows import MainWindows
  File "D:\faster-whisper-GUI-main\faster_whisper_GUI\mainWindows.py", line 34, in <module>
    from faster_whisper import Word
ImportError: cannot import name 'word' from 'faster_whisper' (C:\Users\LtpLGM\.conda\envs\pytorch\lib\site-packages\faster_whisper\__init__.py)

应将mainWindows.py, line 34的 from faster_whisper import Word修改为 from faster_whisper.transcribe import Word

**Comment by LtpLGM** [comment]
可能因上游[faster-whisper](https://github.com/mayeaux/faster-whisper)版本更新，源代码中大量from faster_whisper ...需改为 from faster_whisper.transcribe ...

**Comment by CheshireCC** [comment]
之前我是通过修改源代码来修复错误的，之后统一更换 import 方式吧
