### ISSUE TITLE
执行转写以后没任何反应

### ISSUE THREAD

**Issue by b9348** [CheshireCC/faster-whisper-GUI#220]
CPU使用率0%，GPU使用率0%，我已经正确配置ffmpeg和CUDA，命令行方式可以正常使用的
执行声乐分离 音轨分离时，GPU占用率高达99%，23m的音频10分钟没搞完，我用AU都没这么久，为什么……

我用的是6g的模型，是显存不够吗
![1](https://github.com/user-attachments/assets/fff33658-842a-4267-b436-b4c80ac7d002)

**Comment by b9348** [comment]
执行声乐分离 音轨分离时，GPU占用率高达99%，23m的音频10分钟没搞完，我用AU都没这么久，为什么……

**Comment by CheshireCC** [comment]
左下角，设置页面，看看日志

**Comment by etkane** [comment]
看日志，一般是模型没选对。
