### ISSUE TITLE
部分字幕在对话结束后，不会消失

### ISSUE THREAD

**Issue by yexi-by** [CheshireCC/faster-whisper-GUI#221]
我在提取长视频字幕的时候，发现部分字幕在对话结束后，不会自动消失。要等到下一句对话开始后，才会消失并显示下一段字幕，有方法解决这个问题吗

**Comment by CheshireCC** [comment]
1. 开启科学上网 -> 转写结束之后使用 whisperX 对齐字幕时间戳
2. 表格里的起止时间戳可以手动编辑
3. 尝试调整参数
