### ISSUE TITLE
时间戳对齐报错

### ISSUE THREAD

**Issue by liuweicheng14** [CheshireCC/faster-whisper-GUI#223]
日志如下：
安装了ffmpeg，令牌也更换了
==========2024-09-17_23:06:33==========
==========TimeStample_Alignment==========

TimeStample alignment
transform transcript result...
process audio...
load wav2vec2 model...

Wav2Vec2ForCTC requires the PyTorch library but it was not found in your environment. Checkout the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.

Error loading model from huggingface, check https://huggingface.co/models for finetuned wav2vec2.0 models
alignment Error
Error: The chosen align_model "jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn" could not be found in huggingface (https://huggingface.co/models) or torchaudio (https://pytorch.org/audio/stable/pipelines.html#id14)
UPdata DataModel

**Comment by liuweicheng14** [comment]
电脑上已经安装了python 版本为3.10.11，pip list如下
Package           Version
----------------- ------------
filelock          3.13.1
fsspec            2024.2.0
Jinja2            3.1.3
MarkupSafe        2.1.5
mpmath            1.3.0
networkx          3.2.1
numpy             1.26.3
pillow            10.2.0
pip               23.0.1
setuptools        65.5.0
sympy             1.12
torch             2.4.1+cu124
torchaudio        2.4.1+cu124
torchvision       0.19.1+cu124
typing_extensions 4.9.0

**Comment by liuweicheng14** [comment]
版本是 0.8.1——2024.7.29

**Comment by CheshireCC** [comment]
是这样，软件自带了 python 环境，不会使用系统安装的 python ，你不如检查一下安装目录下的 torch 环境

**Comment by eric09230** [comment]
@andeziod 我也是同樣報錯,改用了0.8.0可以正常使用

**Comment by andeziod** [comment]
> @andeziod 我也是同樣報錯,改用了0.8.0可以正常使用

感谢反馈！看来是0.8.1的通病了，我也换回0.8.0算了

**Comment by sxjeru** [comment]
0.8.5 可以正常使用了。

**Comment by CheshireCC** [comment]
> 0.8.5 可以正常使用了。

OK
