### ISSUE TITLE
不能读取。这个错误怎么解决

### ISSUE THREAD

**Issue by 11123kbbs** [CheshireCC/faster-whisper-GUI#231]
出来一个这样子的错误，这个是什么意思，怎么解决，谢谢
![QQ20240924-004229](https://github.com/user-attachments/assets/ce642294-e7e6-4f25-a65c-d864d8f65cd0)

**Comment by CheshireCC** [comment]
V3 模型选项问题，改一下就好了

**Comment by 11123kbbs** [comment]
V3模型改哪里呀？怎么修改呢。谢谢

**Comment by 11123kbbs** [comment]
是这个选项吗？我已经打开了。但是还是出现了错误
![QQ20240927-100334](https://github.com/user-attachments/assets/8dbca876-908c-4459-bc6f-34974321f74b)

**Comment by 11123kbbs** [comment]
运行了pip install --upgrade --force-reinstall --no-deps git+https://github.com/m-bain/whisperx.git这个好了
