### ISSUE TITLE
仅能使用 cpu推算

### ISSUE THREAD

**Issue by LtpLGM** [CheshireCC/faster-whisper-GUI#233]
显卡：gtx1650
在fastwhispr模型导入页面中不管选择cuda还是auto均无法使用cuda推算。
通过使用tiny和medium两个体积模型的测试，排除爆显存问题。
whisperdesktop可以正常使用cuda，应可排除驱动问题

**Comment by CheshireCC** [comment]
1. whisperdesktop 不使用 CUDA ，
2. 检查一下系统的 GPU 加速设置是否打开
