### ISSUE TITLE
bug报告

### ISSUE THREAD

**Issue by dolphin93** [CheshireCC/faster-whisper-GUI#234]
mainWindows.py的第798行代码有误，原始代码为chunk_length = float(chunk_length); float应该换为int。该参数是表示音频分块长度，默认是30秒

**Comment by CheshireCC** [comment]
由于 faster-whisper 后端没有进行相应处理，因此此处的 chunk_length  将会直接参与后续运算，如果将 chunk_length  设置为 int 则会产生类型错误

**Comment by dolphin93** [comment]
在我的测试中，使用float会产生typeError错误。例如在fastedr-whisper的feature_etractor.py的下面这行：
waveform = np.pad(waveform, [(0, self.n_samples)])，由于self.n_samples = chunk_length * self.sampling_rate，如果chunk_lengh是浮点类型，造成n_samples也是浮点型，造成np.pad报类型错误。 transcribe.py中也类似会类型错误。
      当我把chunk_length改为int方式强制转换后错误消失。但奇怪的是，我下载已经打包好的版本，并不会报这个错误，使用源代码则出错

**Comment by CheshireCC** [comment]
我检查了一下代码，确实是这样，安装 faster-whisper 1.0.3 之后我发现了这个 bug 修改了 feature_extractor.py 当中的代码：

self.n_samples = int(chunk_length * self.sampling_rate)

**Comment by CheshireCC** [comment]
我检查了一下代码，确实是这样，安装 faster-whisper 1.0.3 之后我发现了这个 bug 修改了 feature_extractor.py 当中的代码：

self.n_samples = int(chunk_length * self.sampling_rate)

所以 mainwindows.py 中的代码维持了原样
我个人认为 在 n_samples  这一步再进行取整相对要合理些，应为采样数是由音频的采样率和时长共同决定的， float 类型的时长并没有任何问题，事实上，一个较短小数位的时长乘以 44100 或者 48000 或者 16000 Hz 采样率之后几乎都能得到整值，只需要转换数值类型即可。
