### ISSUE TITLE
特定模型执行转写后卡死崩溃

### ISSUE THREAD

**Issue by sxjeru** [CheshireCC/faster-whisper-GUI#237]
model：https://huggingface.co/kotoba-tech/kotoba-whisper-v2.0-faster
装载上面模型进行转写，VAD 预处理完成后即卡死崩溃，CUDA 刚活动一秒即停止，没有爆内存显存，log 无异常。

烦请作者空闲时帮忙检查一下，感谢作者提供此工具。❤️

此外附带问下，如果频繁漏转写（即有些对话没有被转成文字），建议调节哪些参数，非常感谢。

**Comment by CheshireCC** [comment]
降低 VAD 阈值

**Comment by sxjeru** [comment]
已在 #239 得到解答。

> 貌似关掉 单词时间戳 选项就可以了。
