### ISSUE TITLE
是否能支持 kotoba-tech/kotoba-whisper-v2.1 这个模型？

### ISSUE THREAD

**Issue by tomeleon** [CheshireCC/faster-whisper-GUI#239]
在抱脸上面看到的，似乎是针对whisper的一个日语分支模型，从1.0已经更新现在的2.1版本了。

**Comment by CheshireCC** [comment]
https://huggingface.co/kotoba-tech/kotoba-whisper-v2.0-faster

**Comment by tomeleon** [comment]
嗯，找到这个了，模型加载是正常的，但是走到读取文件识别阶段，运行1分钟左右，软件就闪退了。

**Comment by CheshireCC** [comment]
> 嗯，找到这个了，模型加载是正常的，但是走到读取文件识别阶段，运行1分钟左右，软件就闪退了。
闪退之后看看日志

**Comment by tomeleon** [comment]
哦，似乎不支持 单词级时间戳细分的功能，关闭单词级时间戳就好了。识别速度非常快，但是从结果来看，似乎并没有比largeV3更好。

**Comment by tumibloom** [comment]
我在使用0.8.0版本并取消勾选“使用v3”后可以正常使用这个模型，你可以试试

**Comment by tomeleon** [comment]
OK. 终于可以用了。貌似关掉 单词时间戳 选项就可以了。
不过转写效果并没有比largev3更好，不知道是不是哪里调参不够或者是模型本来就不行。

**Comment by tumibloom** [comment]
> OK. 终于可以用了。貌似关掉 单词时间戳 选项就可以了。
> 不过转写效果并没有比largev3更好，不知道是不是哪里调参不够或者是模型本来就不行。

我感觉还行吧，比v3快很多，也可能我3060laptop性能不太行，转写效果确实这俩差不太多

**Comment by sxjeru** [comment]
> Kotoba-Whisper 的速度比 large-v3 快 6.3 倍，同时保持与 large-v3 一样低的错误率。

kotoba-whisper 的目标就是这样，想要比 large v3 更好应该不太现实。

**Comment by CheshireCC** [comment]
https://huggingface.co/CheshireCC/kotoba-whisper-v2.1-faster/tree/main

**Comment by CheshireCC** [comment]
> OK. 终于可以用了。貌似关掉 单词时间戳 选项就可以了。 不过转写效果并没有比largev3更好，不知道是不是哪里调参不够或者是模型本来就不行。

确实是 `单词级时间戳` 的问题，v2.1 版本模型也仍然存在这个问题，
