### ISSUE TITLE
不稳定

### ISSUE THREAD

**Issue by meta10110** [CheshireCC/faster-whisper-GUI#24]
经常闪退
按照作者的设置后，还是出现经常闪退
已确定不是电脑配置问题
特别是更换模型后，转化过程中必然闪退

**Comment by CheshireCC** [comment]
因为更新了前端的原因，无边框窗口方案可能和目前的版本不兼容，造成这个问题，
闪退的时候可以去打开软件目录看一眼 fasterwshipergui.log 文件，看看执行到哪一步了
更换模型之后确实容易造成闪退，这个很有可能是 CT2 引擎的原因，这个问题一直存在，很难修复，尤其当温度回退配置生效时，下一个版本可能会尝试集中解决一些稳定性问题

**Comment by CheshireCC** [comment]
0.4.3 版本将会暂时停止使用无边框窗口，以期改善软件崩溃频繁的问题

**Comment by CheshireCC** [comment]
较长时间未接到闪退报告，将暂时关闭 issue
