### ISSUE TITLE
无法启动，亮了一瞬间图标就闪退

### ISSUE THREAD

**Issue by Kooluve** [CheshireCC/faster-whisper-GUI#242]
8.1和8.0都试了。没有报错日志。杀毒软件没提示问题，系统win11。

**Comment by CheshireCC** [comment]
1. 管理员身份运行
2. 换个不要管理员权限的硬盘重新安装
3. 属性，安全，看看最下面有没有一个选项，如果有去掉勾

**Comment by Kooluve** [comment]
> 1. 管理员身份运行
> 2. 换个不要管理员权限的硬盘重新安装
> 3. 属性，安全，看看最下面有没有一个选项，如果有去掉勾

装在c盘默认位置的。以管理员启动成功了，感谢。

**Comment by CheshireCC** [comment]
> > 1. 管理员身份运行
> > 2. 换个不要管理员权限的硬盘重新安装
> > 3. 属性，安全，看看最下面有没有一个选项，如果有去掉勾
> 
> 装在c盘默认位置的。以管理员启动成功了，感谢。

最好换个盘重装，因为管理员身份运行会导致文件拖放功能失效
