### ISSUE TITLE
无法调用nvdia显卡?

### ISSUE THREAD

**Issue by heragehome** [CheshireCC/faster-whisper-GUI#248]
转写可以正常进行下来,默认参数,v3模型,输入语言设为日语,但是日漫识别出来了一些零零碎碎的英文字母.全程显存有占用但3d那一栏没有任何占用,之前使用其他家的whispere也有这个问题,就whisperedesktop可以正常运行

**Comment by sxjeru** [comment]
3D 有占用而不是 Cuda？是开启“硬件加速GPU计划”了么。

识别出英文可以看看模型有无 distil 等剪枝（只支持 en），是不是原始的 v3 模型。

**Comment by heragehome** [comment]
是显存有占用,3d无占用,win确实开启了硬件加速
其他的就不清楚了...

**Comment by GillianJiao** [comment]
> 是顯存有佔用,3d無佔用,win確實開啟了硬體加速 其他的就了...

有8.1版本确实有时候不掉用n卡，可以降会老版本

**Comment by CheshireCC** [comment]
新版本已经修复
