### ISSUE TITLE
ModuleNotFoundError: No module named 'qfluentwidgets'

### ISSUE THREAD

**Issue by ODIIIPUNCH** [CheshireCC/faster-whisper-GUI#25]
你好点开FasterWhisperGUI，显示报错ModuleNotFoundError: No module named 'qfluentwidgets'，这个怎么解决？

**Comment by CheshireCC** [comment]
你的安装可能有问题，请尝试完全卸载之后重新安装

**Comment by ODIIIPUNCH** [comment]
怎么完全卸载？我是下载的压缩包解压的

**Comment by CheshireCC** [comment]
? 0.4.0吗？
请下载安装包
