### ISSUE TITLE
软件权限问题

### ISSUE THREAD

**Issue by JasonxlxCharles** [CheshireCC/faster-whisper-GUI#254]
我的电脑对于这个软件的权限认定很混乱，如果不选择管理员权限，快捷方式根本打不开；就算选择了管理员权限，字幕只能输出未经WhisperX处理的，而whisperX时间戳对齐后的字幕就再也见不着了

个人认为可能是权限问题，或许管理员权限没有给到whisperX？还是说因为我的电脑只有一个C盘，所以whisperX无法读取或者修改文件？不过，为什么会出现不用管理员运行根本打不开的情况呢？

非常感谢

另外，有考虑创一个telegram群或者其他群组吗？这样能更方便交流参数调试等方面的问题

**Comment by CheshireCC** [comment]
whisperX 的问题是 torch 打包的问题，将会在下一个版本中修复
管理员权限问题是因为软件启动时需要从安装目录下读写配置文件。装到系统盘之后就会由于没有权限读写文件，直接打不开了
群组管理很麻烦，AI 技术容易被滥用，所以不建立群组，避免一些不必要的麻烦
