### ISSUE TITLE
是否可以手动下载WhisperX的模型？

### ISSUE THREAD

**Issue by BrotherX** [CheshireCC/faster-whisper-GUI#255]
CheshireCC你好，感谢你的项目。
我公司电脑可能是受到防火墙设置限制，无法下载WhisperX的模型，日记如下：
Speaker diarize and alignment
load speaker brain model...
failed to diarize speaker!
Error: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /pyannote/speaker-diarization/resolve/2.1/config.yaml (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))"), '(Request ID: 9a2d7992-8743-46a4-b9d9-bd24a30052d6)')
UPdata DataModel

我是否可以手动下载所需模型？应该放在什么地方？感谢回答。

**Comment by CheshireCC** [comment]
模型放在安装目录下的 cache 文件夹下

**Comment by BrotherX** [comment]
多谢回复，问题已经解决，我做了以下尝试：
1. 手动下载了models--pyannote--speaker-diarization，放在cache文件夹下。报错
2. 手动下载了models--pyannote--segmentation，还是放在cache文件夹下。报错
3. 在以上的基础上，把另一台电脑上的{user}/.cache/huggingface和{user}/.cache/torch全部拷贝到目标电脑上的{user}/.cache/下，在离线状态下可以完成WhisperX说话人分离，在线状态下还是报错。

**Comment by CheshireCC** [comment]
在线状态下可能是因为贵司网络不能访问 huggingface 导致模型在线 Hash 验证失败造成的，需要科学上网才能正常使用 WhisperX 功能

**Comment by gsxgmpkt9020** [comment]
> 多谢回复，问题已经解决，我做了以下尝试：
> 
> 1. 手动下载了models--pyannote--speaker-diarization，放在cache文件夹下。报错
> 2. 手动下载了models--pyannote--segmentation，还是放在cache文件夹下。报错
> 3. 在以上的基础上，把另一台电脑上的{user}/.cache/huggingface和{user}/.cache/torch全部拷贝到目标电脑上的{user}/.cache/下，在离线状态下可以完成WhisperX说话人分离，在线状态下还是报错。

1. 如果离线成功，在线失败，你把huggface域名加到防火墙里面阻止能不能实现变相离线？
2. 我这边cache文件夹下还有hdemucs_high_trained.pt
