### ISSUE TITLE
2 language transcribe 

### ISSUE THREAD

**Issue by marsonal2023** [CheshireCC/faster-whisper-GUI#30]
I have Arabic audio but contains some English sentences and words. in the the previous version with whisper large v2 it could detect those words and transcribe them. now in the new version with whisper v3 it only transcribes the Arabic speech omitting the English words is this issue due to a new program update or the new whisper version?

**Comment by CheshireCC** [comment]
I’ll test for this.
Now ，just float16 models on HG，may be we need float32 model.I'm not sure.

**Comment by marsonal2023** [comment]
i found that the issue is whisper v3 itself but i dont know why ... i tried many versions of v3 and v2 .... v3 is bad getting english words in arabic context but v2 do it well

**Comment by marsonal2023** [comment]
another bad thing of whisper v3 ... there are some arabic letters that sound nearly the same .... like letters of س and ص ... letters of ز and ظ ... v2 used to write the words properly but v3 if there is a word with ص it always write it wrong with س and sso on.

**Comment by marsonal2023** [comment]
although v3 gets more arabic words right in general but sadly it has other errors that wasnt in v2

**Comment by CheshireCC** [comment]
In fact, there are also relevant feedback showing that in Japanese recognition, V3 has more error rates, and I am not sure whether the 32-bit model will perform better

**Comment by CheshireCC** [comment]
I tried to transcribe Japanese with V3，I found that it performed as same well as V2 model，they two both take some error，but not same😑. And V3 model can also get English words correctly from Japanese, but just simple words， like "Ok".
