### ISSUE TITLE
Support Large v3

### ISSUE THREAD

**Issue by dubr1k** [CheshireCC/faster-whisper-GUI#32]
Hello!
Yesterday installed the program version 0.7.4, loaded local model faster-whisper-large v3 from HG.
Your application loaded this model. Then I uploaded audio in Russian, the program recognized it and so and hung. Nothing else happened.

**Comment by CheshireCC** [comment]
open software folder, find fasterwhispergui.log file, may get more information.
BTW, latest version is 0.4.3

**Comment by marsonal2023** [comment]
make sure you set "Use v3" to true before loading model

**Comment by dubr1k** [comment]
> make sure you set "Use v3" to true before loading model

large v3 true on the settings

**Comment by dubr1k** [comment]
> open software folder, find fasterwhispergui.log file, may get more information. BTW, latest version is 0.4.3

0.7.3 Sorry. 

After attaching the file, nothing happens at all.

Attaching the log
==========2023-11-14_11:30:42==========
==========LoadModel==========

model_size_or_path: D:/Programs/Whisper/bababababooey
device: cuda
device_index: 0
compute_type: float32
cpu_threads: 4
num_workers: 1
download_root: C:/Users/dubr1/.cache/huggingface/hub
local_files_only: False

Load over
D:/Programs/Whisper/bababababooey
max_length:             448
num_samples_per_token:  320
time_precision:  0.02
tokens_per_second:  50
input_stride:  2

[Using V3 model, modify  number of mel-filters to 128]

==========2023-11-14_11:31:32==========
==========Process==========

Traceback (most recent call last):
  File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 347, in run
  File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\concurrent\futures\_base.py", line 458, in result
  File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\concurrent\futures\thread.py", line 58, in run
  File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 221, in transcribe_file
  File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\faster_whisper\transcribe.py", line 311, in t
<img width="449" alt="Снимок экрана 2023-11-14 в 11 32 58" src="https://github.com/CheshireCC/faster-whisper-GUI/assets/146764463/9c7cbb2d-84e3-429d-8fca-a7f6b04485cc">

**Comment by CheshireCC** [comment]
will it work with v2 models?

**Comment by CheshireCC** [comment]
> Traceback (most recent call last):
> File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 347, in run
> File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\concurrent\futures_base.py", line 621, in result_iterator
> File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\concurrent\futures_base.py", line 319, in _result_or_cancel
> File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\concurrent\futures_base.py", line 458, in result
> File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\concurrent\futures_base.py", line 403, in __get_result
> File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\concurrent\futures\thread.py", line 58, in run
> File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\faster_whisper_GUI\transcribe.py", line 221, in transcribe_file
> File "D:\Programs\Whisper\faster-whisper-0.9.0\faster_whisper\FasterWhisperGUI\faster_whisper\transcribe.py", line 311, in t

after that, I think there may be more information , It's important, paste it here. You can also copy and paste log file here,but not text.

**Comment by dubr1k** [comment]
> will it work with v2 models?

Yeah, without problems

**Comment by CheshireCC** [comment]
#26 this is a issue that had been closed, he took same problem with you , after modified file names , it work

**Comment by dubr1k** [comment]
> > > will it work with v2 models?
> > 
> > 
> > Yeah, without problems
> 
> check your folder of v3 model, may some file-names of config file wrong, it whould with 3 config files, ext with `.json`

THX. all is working
