### ISSUE TITLE
0.43版v3模型没有生成字幕

### ISSUE THREAD

**Issue by HIjamespeng** [CheshireCC/faster-whisper-GUI#33]
测试了0.43版v3模型，开始处理音频...
Detected language [Chinese] with probability [100.00%]
Audio duration     —— [00:30:00.3627] 
after VAD duration —— [00:29:05.744]
Transcription for... 
音频处理正在处理中，一直停留在这个步骤，没有字幕生成，显卡占用率没有变化
fasterwhispergui.log显示为
[fasterwhispergui.log](https://github.com/CheshireCC/faster-whisper-GUI/files/13343383/fasterwhispergui.log)

**Comment by CheshireCC** [comment]
可能是由于您的参数引起的，能把参数信息也粘贴到这里吗

**Comment by CheshireCC** [comment]
可能是由于参数引起的，比如使用了初始提示词之类的
能把参数信息也粘贴到这里吗

**Comment by HIjamespeng** [comment]
用您提供的链接（https://pan.baidu.com/s/1_kaG5qLqxWbMP729p6N5FQ?pwd=ebdh，提取码：ebdh）模型成功了，请问打开软件后本地模型能自动加载吗，并且是否使用V3模型、计算精度、音频语言、输出文件格式等参数可以自动使用上一次的，不用每次都选，谢谢！

**Comment by CheshireCC** [comment]
> 用您提供的链接（[https://pan.baidu.com/s/1_kaG5qLqxWbMP729p6N5FQ?pwd=ebdh，提取码：ebdh）模型成功了，请问打开软件后本地模型能自动加载吗，并且是否使用V3模型、计算精度、音频语言、输出文件格式等参数可以自动使用上一次的，不用每次都选，谢谢！](https://pan.baidu.com/s/1_kaG5qLqxWbMP729p6N5FQ?pwd=ebdh%EF%BC%8C%E6%8F%90%E5%8F%96%E7%A0%81%EF%BC%9Aebdh%EF%BC%89%E6%A8%A1%E5%9E%8B%E6%88%90%E5%8A%9F%E4%BA%86%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%89%93%E5%BC%80%E8%BD%AF%E4%BB%B6%E5%90%8E%E6%9C%AC%E5%9C%B0%E6%A8%A1%E5%9E%8B%E8%83%BD%E8%87%AA%E5%8A%A8%E5%8A%A0%E8%BD%BD%E5%90%97%EF%BC%8C%E5%B9%B6%E4%B8%94%E6%98%AF%E5%90%A6%E4%BD%BF%E7%94%A8V3%E6%A8%A1%E5%9E%8B%E3%80%81%E8%AE%A1%E7%AE%97%E7%B2%BE%E5%BA%A6%E3%80%81%E9%9F%B3%E9%A2%91%E8%AF%AD%E8%A8%80%E3%80%81%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F%E7%AD%89%E5%8F%82%E6%95%B0%E5%8F%AF%E4%BB%A5%E8%87%AA%E5%8A%A8%E4%BD%BF%E7%94%A8%E4%B8%8A%E4%B8%80%E6%AC%A1%E7%9A%84%EF%BC%8C%E4%B8%8D%E7%94%A8%E6%AF%8F%E6%AC%A1%E9%83%BD%E9%80%89%EF%BC%8C%E8%B0%A2%E8%B0%A2%EF%BC%81)

我的设想是，可以将模型参数等保留，但是自动加载模型这个问题我还没想过是否应该让软件绕过用户自动进行，因为 Denucs 是一个很占计算资源的功能，如果软件自动加载了模型的话，那么用户将会需要手动卸载模型再才好运行 Demucs 功能，但 我不确定 Demucs 功能使用的频次，我自己是会频繁使用 Demucs 功能的啦
可能我需要再添加一个设置页面，用来让用户开关模型自动加载以及保存配置等功能，这样就可让只使用一个模型的用户每次都能自动加载模型及参数配置了

**Comment by CheshireCC** [comment]
BTW：首页上面我更新了 32 位模型的下载地址

**Comment by HIjamespeng** [comment]
谢谢您的耐心回答！考虑得很周到！

**Comment by CheshireCC** [comment]
现在我将关闭本 issue，如果有其他问题请开启新的 issue 进行讨论
