### ISSUE TITLE
希望能增加语言设置选项

### ISSUE THREAD

**Issue by Jiang10086** [CheshireCC/faster-whisper-GUI#34]
如题，默认是英文界面，不如中文易懂，希望能手动切换语言。
开发者辛苦了

**Comment by CheshireCC** [comment]
windows 11：
设置 -> 时间和语言 -> 语言和区域 -> 区域格式 -> 中文（简体，中国）
重新启动软件，因该能看到中文界面， windows 10 应该与之类似

**Comment by Jiang10086** [comment]
> windows 11： 设置 -> 时间和语言 -> 语言和区域 -> 区域格式 -> 中文（简体，中国） 重新启动软件，因该能看到中文界面， windows 10 应该与之类似

看来软件是自动检测的，但能不能不换系统语言而在软件内单独设置呢？

**Comment by CheshireCC** [comment]
这个，和自动检测功能可能会冲突，我也没测试过，等有时间了试一下吧

**Comment by CheshireCC** [comment]
新增设置页面
新增选择语言的设置项
