### ISSUE TITLE
0.4.0 WhisperX alignment Error 以及保存字幕文件无反应

### ISSUE THREAD

**Issue by boomho** [CheshireCC/faster-whisper-GUI#36]
转写完成后在WhisperX处理界面分别点击了时间戳对齐和保存字幕文件，前台均提示成功，但没有输出任何文件。
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/33543503/7ea9ffcf-b7d1-41f7-9c53-00a058ebdbf3)

**log如下：**
==========2023-11-14_17:20:49==========
==========TimeStample_Alignment==========

alignment Error
Error: [WinError 2] 系统找不到指定的文件。
UPdata DataModel

==========OutputSubtitleFiles==========

【Over】

==========2023-11-14_17:21:36==========
==========TimeStample_Alignment==========

alignment Error
Error: [WinError 2] 系统找不到指定的文件。
UPdata DataModel

==========OutputSubtitleFiles==========

【Over】

-----
目前我只能手动在temp文件里找转写那一步自动保存的srt。

**Comment by CheshireCC** [comment]
WhisperX 功能需要连接 huggingface 下载模型，不能下载或验证时可能出现问题。
由于 国内互联网 环境原因，不能直接访问 huggingface ，您可能需要使用些 **科学** 手段
BTW：最新版本已经更新到 0.4.3

**Comment by CheshireCC** [comment]
whisperX 失败的话，当前的表格和内存中的转写结果可能会被异常返回的空值取代，所以这个时候保存文件就会出错

**Comment by boomho** [comment]
目前我的网络访问huggingface.com是可以正常打开的的，所以不知道还可以怎么处理。另外whisperX可否手动选择指定的本地模型呢？

**Comment by CheshireCC** [comment]
whisperX 是每种不同语言需要一种对应模型来进行音素识别，然后再根据音素识别结果来进行时间戳对齐，所以考虑到多语种用户可能会需要反复下载不同模型，就干脆设置成自动下载了，whisperX 引擎的原本设计也就是在线下载的

你的这个找不到指定文件的错误会不会和你的文件名有些关系？我觉得可能是文件名的锅，因为 whisperX 使用了 ffmpeg 处理音频文件，有的时候可能会出错

**Comment by CheshireCC** [comment]
> 目前我的网络访问huggingface.com是可以正常打开的的，所以不知道还可以怎么处理。另外whisperX可否手动选择指定的本地模型呢？

哇，我发现你这个 huggingface.com 是个很有意思的网站😂

**Comment by boomho** [comment]
> > 目前我的网络访问huggingface.com是可以正常打开的的，所以不知道还可以怎么处理。另外whisperX可否手动选择指定的本地模型呢？
> 
> 哇，我发现你这个 huggingface.com 是个很有意思的网站😂

抱歉，多打了一个m😂😂 确实是huggingface.co没错，因为我也刚刚在那里生成了用户令牌😂
---
关于找不到指定文件的错误，我刚刚做了一下测试，目前结果还是跟一开始写的issue是一样的。
为了方便判定，我把我的操作步骤、文件路径和log都提供一下。（BTW我已经升到0.4.3了，目前连接huggingface的网络也正常）

**我的操作步骤如下：**
1、打开fasterwhispergui.exe。
2、使用Demucs分离音频。（原文件路径为D:\encore\lottegumA.mp4；默认参数；输出目录留空；成功提取D:\encore\VocalslottegumA._vocals.wav）
3、加载并使用本地模型（D:/WhisperCache/whisper-large-v2-ct2-i8；计算精度更改为int8，其他默认；加载模型成功）
4、VAD参数修改最大语音块时长为5s，最小静息时长为800ms，Huggingface用户令牌更改为我在https://huggingface.co/settings/tokens 申请的write令牌。（之前已经填写过WhisperX问卷）
5、FasterWhisper页面，音频语言修改为ko-Korean，其余全部默认。
6、Transcription页面，将D:\encore\VocalslottegumA._vocals.wav拖放进框内后点击开始，然后前台提示转写完成，D:\Program Files (x86)\FasterWhisperGUI\temp生成了lottegumA._vocals.srt文件。
7、WhisperX And Output页面，输出目录为空，下面自动加载了lottegumA._vocals.wav文件及转录出来的表单内容，参数全部默认。我首先点击了“保存字幕文件”，前台提示“保存完成 字幕文件已保存”，并在D:\encore\Vocals目录找到了新生成的，以“lottegumA._vocals”为名称的lrc、smi、srt、txt、vtt五个文件。然后我继续点击了“WhisperX时间戳对齐”，前台提示“WhisperX 时间戳对齐结束”；点击“保存字幕文件”，前台提示“保存完成 字幕文件已保存”。但去到D:\encore\Vocals目录并没有新的文件生成（中间操作间隔了2分钟，所以我从修改时间上判断srt没有被覆写），D:\encore也没有srt字幕文件。

**基于你说的可能是文件名的原因**，在完成上述步骤后，我在D:\encore\Vocals目录复制了lottegumA._vocals.wav和lottegumA._vocals.srt，并分别更改名称为lottegumA.wav和lottegumA.srt。然后回到刚刚的WhisperX And Output页面，点击加号读取了lottegumA.wav和lottegumA.srt，然后点击了“WhisperX时间戳对齐”，前台提示“WhisperX 时间戳对齐结束”；然后再点击“保存字幕文件”，前台提示“保存完成 字幕文件已保存”。但结果跟刚刚一样，没有新文件生成，复制的lottegumA.srt从修改时间上看也没有被覆写。

打开软件目录里的log文件依旧如下：

==========2023-11-14_18:26:30==========
==========TimeStample_Alignment==========

alignment Error
Error: [WinError 2] 系统找不到指定的文件。
UPdata DataModel

**Comment by CheshireCC** [comment]
好的，我来进行测试

**Comment by CheshireCC** [comment]
你是不是没安装过 ffmpeg ？

链接：https://pan.baidu.com/s/1YVxFAbi7THs_MMffBIrkeQ?pwd=jeio 

 如果没安装过 ffmpeg 请将上述链接中的文件夹下载，放入软件安装目录，之后再进行测试

**Comment by boomho** [comment]
> 你是不是没安装过 ffmpeg ？
> 
> 链接：https://pan.baidu.com/s/1YVxFAbi7THs_MMffBIrkeQ?pwd=jeio
> 
> 如果没安装过 ffmpeg 请将上述链接中的文件夹下载，放入软件安装目录，之后再进行测试

破案了，把上面ffmpeg整个文件夹放进软件安装目录后已经成功用上了WhisperX！时间戳对齐和保存字幕功能都成功了。
我没有正式安装过ffmpeg，之前下的Megui和Topaz Video AI好像都是自带了ffmpeg文件夹和相关文件，安装时直接放在它们自己目录名下了（也因此我电脑里能搜出一堆ffmpeg分布在不同地方😂），所以之前没有想过要安装ffmpeg的事情。

**Comment by CheshireCC** [comment]
好的，那么现在我将关闭本 issue，如果有其他问题请打开新的 issue 进行讨论

**Comment by neavo** [comment]
> 好的，那么现在我将关闭本 issue，如果有其他问题请打开新的 issue 进行讨论

卧槽竟然真的是ffmpeg的问题，之前搞了好久，主要是也没个提示

最后一页一页翻issue才翻到这里

建议在readme里面说明一下 。。。。。

**Comment by CheshireCC** [comment]
> > 好的，那么现在我将关闭本 issue，如果有其他问题请打开新的 issue 进行讨论
> 
> 卧槽竟然真的是ffmpeg的问题，之前搞了好久，主要是也没个提示
> 
> 最后一页一页翻issue才翻到这里
> 
> 建议在readme里面说明一下 。。。。。

这个可以有
