### ISSUE TITLE
ImportError: cannot import name 'TranscriptionInfo' from 'faster_whisper' 

### ISSUE THREAD

**Issue by maxoo1001** [CheshireCC/faster-whisper-GUI#37]
有2个问题，帮忙看一下，
尝试安装了requirements.txt   发现里面的很多包有问题。。官网上面找不到这个包。。joblib==1.12.0   要么是1.1.0  要么是1.2.0  没有这个1.12

另外我在启动的过程中会报==========2023-11-14_18:38:45==========
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Traceback (most recent call last):
  File "d:\faster-whisper-GUI-main\FasterWhisperGUI.py", line 81, in <module>
    from faster_whisper_GUI.mainWindows import MainWindows
  File "d:\faster-whisper-GUI-main\faster_whisper_GUI\mainWindows.py", line 29, in <module>
    from faster_whisper import TranscriptionInfo
ImportError: cannot import name 'TranscriptionInfo' from 'faster_whisper' (D:\conda_env\envs\fastgui\lib\site-packages\faster_whisper\__init__.py)
我去目录下面看了 确实没有这个TranscriptionInfo    这个是怎么回事？

**Comment by maxoo1001** [comment]
搞定了。。那个引用文件要改一下from faster_whisper.transcribe import WhisperModel,TranscriptionInfo,Segment,Word

**Comment by CheshireCC** [comment]
> 搞定了。。那个引用文件要改一下from faster_whisper.transcribe import WhisperModel,TranscriptionInfo,Segment,Word

requirements 文件确实长时间没有更新了 另外也因为一些包的依赖关系，下载太费劲所以我都使用 whl 进行本地安装，比如 torch-GPU 和 torchaudio-GPU 。所以很多包都不对了
