### ISSUE TITLE
0.4.3 閃退 提供LOG 配置

### ISSUE THREAD

**Issue by huhu12301231** [CheshireCC/faster-whisper-GUI#38]
高機率在轉寫完成後閃退 溫度回退已設定0  模型V2 V3皆會temp裡的暫存都已經是完整的字幕檔
配腦配置:win11 9900k 32G ram  3080 10g 驅動都是最新
[參數參數.txt](https://github.com/CheshireCC/faster-whisper-GUI/files/13366358/default.txt)
[fasterwhispergui.log](https://github.com/CheshireCC/faster-whisper-GUI/files/13366359/fasterwhispergui.log)

多一個D
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/67462065/cd882288-c6ca-4f2c-9df8-be717eef55c1)

**Comment by CheshireCC** [comment]
好家伙，拼写错误🤣🤣我自己从来都没注意过，感谢指正

关于这个闪退的问题，大概率是因为自动跳转到输出页面的时候窗体崩了，偶尔会出现这个问题，目前停用无边框窗口之后应该改善很多了，我考虑可能将该功能去掉，或者设置为可选项，

**Comment by CheshireCC** [comment]
拼写错误已经纠正，
闪退问题希望设置自动跳转后能有所改善
