### ISSUE TITLE
提示“不包含音频流的文件将被忽略”

### ISSUE THREAD

**Issue by zhangeden** [CheshireCC/faster-whisper-GUI#40]
有部分视频会出现这样的误判，但我确定这个文件里面是有音频的，并且能在其他软件中用whisper V3转写出内容。

.mp4文件

![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/59479806/912a9020-08b7-4414-9dd0-f0395782ed38)

**Comment by CheshireCC** [comment]
因为采用了自动音频内容检测，主要是避免一些无音频的视频乱入，但是有些编码、压缩不那么正规的视频软件转出的视频就会有这个问题，可能是丢失了元数据的原因，这个确实不是 whisper 的问题，是我的问题
但是我还没有找到很好的兼容性方案来处理这个问题，可能下个版本把音频内容检测也设置成可选项吧，这样可能更好些，

另外，您如果方便的话可以把视频内容分享给我以允许我进行测试、修复。比如上传百度云并分享，如果不方便的话就算了。

就目前而言，您可以尝试将视频内的音频内容导出成单独的音频文件，然后进行转写。快速方法就是使用命令行工具
`ffmpeg -i <xxx.mp4> <xxx.wav>`

**Comment by CheshireCC** [comment]
已经有相关修复，且该 issue 长时间未回应，现在关闭
