### ISSUE TITLE
 有计划加入distil-whisper吗

### ISSUE THREAD

**Issue by isbn9877007** [CheshireCC/faster-whisper-GUI#41]
这个Distil-Whisper和fast-whisper哪个效果更好，希望能得到大佬的回答，谢谢大佬的付出

**Comment by CheshireCC** [comment]
Distil-Whisper 还很不成熟，目前也只支持英语输出，实际上重新训练模型的话，考虑到训练与数据有直接关系而不仅仅只是模型结构，所以很难说会比 whisper 本身更好，但也许他们会有改进方案。我对该项目了解不多，暂时也没有更换转写后端的想法

**Comment by isbn9877007** [comment]
感谢大佬的回答，我正在关注[insanely-fast-whisper](https://github.com/Vaibhavs10/insanely-fast-whisper)这个改进的whisper，如果他们后续确实证明了他们的工作在没有降低准确度的情况下能够有如此大幅度的加速并且支持cpp，我希望能帮助大佬添加该转写后端，毕竟按照他们的说法这个加速能力确实强，再次感谢大佬
