### ISSUE TITLE
启动错误：'gbk' codec can't encode character '\U0001f4e2' in position 9: illegal multibyte sequence

### ISSUE THREAD

**Issue by jiangningqu70** [CheshireCC/faster-whisper-GUI#47]
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/134199661/13b43616-5193-4b1b-b299-354b72f7805f)
请问一下这是什么错误？哪个代码的问题呢

**Comment by CheshireCC** [comment]
这是编码问题，你运行到哪个步骤？把log文件贴出来看看

**Comment by CheshireCC** [comment]
太长时间没有回应，将关闭该issue
