### ISSUE TITLE
输出的字幕会覆盖空白的区域和Kernel size报错

### ISSUE THREAD

**Issue by FreemanZ** [CheshireCC/faster-whisper-GUI#50]
我们主要用于视频的字幕制作，目前遇到的情况是输出的字幕会把语音前后的时长一并连进去，比如视频里空白了4秒然后说了2秒，那么输出的字幕会在这一共6秒的时间内都显示这两秒语音的内容
![企业微信截图_17025497955843](https://github.com/CheshireCC/faster-whisper-GUI/assets/7681383/d7757e75-a6e7-4dcc-8ad0-b935fa2dde57)
请问需要修改什么设置吗？
感谢开发者

**Comment by CheshireCC** [comment]
这是断句造成的，如果开启时间戳细分不能解决问题的话，可以尝试开启单词级时间戳或者使用 whisperX 进行时间戳对齐，但是 WisperX 在不同语言之间表现差异很大，会带来别的问题，可能会需要手动修正字幕时间的情况出现
这种断句是因为语音前后的空白被一起算进一句里面进行处理了，可以尝试调整 VAD 参数里几个关于时长的参数，或者试试将语音内容分离出来之后再进行转写，看能否提升 VAD 识别语音段的效果
faster-whisper 的日志里面保存了 VAD 语音分段的情况
转写参数里面也提供了一些参数可以用于模型识别非语音内容，不过使用 VAD 之后不太用得上了

**Comment by FreemanZ** [comment]
感谢回复，我们在使用了whisperX的对齐功能后解决了上述问题，
但是带来了新的问题，
在进行约500个视频的批量处理后，初次进入字幕后处理时可以正常保存文件，但进行了时间戳对齐后，在第241个文件的处理结果后出现了报错：
TimeStample alignment
transform transcript result...
process audio...
start alignment...
alignment Error
Error: Calculated padded input size per channel: (1). Kernel size: (2). Kernel size can't be greater than actual input size
UPdata DataModel
请问是哪里出了问题吗？
系统是9700F 48GB内存 3070Ti

**Comment by CheshireCC** [comment]
> 感谢回复，我们在使用了whisperX的对齐功能后解决了上述问题， 但是带来了新的问题， 在进行约500个视频的批量处理后，初次进入字幕后处理时可以正常保存文件，但进行了时间戳对齐后，在第241个文件的处理结果后出现了报错： TimeStample alignment transform transcript result... process audio... start alignment... alignment Error Error: Calculated padded input size per channel: (1). Kernel size: (2). Kernel size can't be greater than actual input size UPdata DataModel 请问是哪里出了问题吗？ 系统是9700F 48GB内存 3070Ti
> 
> 可能是爆显存了，开始批处理220个字幕的时候显存没有回收，占用5.3GB， 然后变成5.8G、6.3G、6.8G、7.1G、7.4G、7.6G... 那么在之前的500个字幕的批处理中，到241个的时候爆显存是符合这个趋势的

尽管已经进行了许多优化上的尝试，但是 pytorch 本身存在的显存泄露问题很难彻底避免，所以大批量处理的时候就难免会出现显存爆炸的情况了

**Comment by FreemanZ** [comment]
感谢回复，
未来能够尝试在完成转写之后回收一下显存吗？毕竟跑完之后5.3G的占用确实有点高，如果这时候3070Ti的空闲显存能有6GB的话，这个事情就很好办了，
不过目前这个数量也能接受了，至少知道哪里的问题了。

**Comment by CheshireCC** [comment]
> 感谢回复， 未来能够尝试在完成转写之后回收一下显存吗？毕竟跑完之后5.3G的占用确实有点高，如果这时候3070Ti的空闲显存能有6GB的话，这个事情就很好办了， 不过目前这个数量也能接受了，至少知道哪里的问题了。

转写结束之后，运行 whisperX 之前可以卸载 whisper 模型以释放部分显存，相关功能按钮在 输出页面 whisperx 功能旁边，不知道你看到没有

**Comment by FreemanZ** [comment]
> > 感谢回复， 未来能够尝试在完成转写之后回收一下显存吗？毕竟跑完之后5.3G的占用确实有点高，如果这时候3070Ti的空闲显存能有6GB的话，这个事情就很好办了， 不过目前这个数量也能接受了，至少知道哪里的问题了。
> 
> 转写结束之后，运行 whisperX 之前可以卸载 whisper 模型以释放部分显存，相关功能按钮在 输出页面 whisperx 功能旁边，不知道你看到没有

哦吼，感谢回复，还真的没注意到这个，一会可以试试看，
或者能不能在转写完成后添加一个保存作业项目的功能，把转写出来的字幕和视频的对应关系存出去，现在批量处理中断之后只能一个一个添加字幕和对应的视频文件，我们这边几十个一起跑，没法立即重新开始跑对齐。

**Comment by CheshireCC** [comment]
这个可以考虑吧

**Comment by FreemanZ** [comment]
我在卸载模型之后再使用字幕后处理，现在看起来不像是显存问题了，
相同的5个文件，每次放进来一个或者两个的时候，能够跑完对齐功能，并且可以把修改后的字幕保存出来，
但当我把这5个文件全部添加之后批量对齐，log中就会出现这个报错

```
TimeStample alignment
transform transcript result...
process audio...
start alignment...
alignment Error
Error: Calculated padded input size per channel: (1). Kernel size: (2). Kernel size can't be greater than actual input size
UPdata DataModel
```

同时已经完成对齐的文件无法保存出来

这时候再对队列中剩余的字幕执行对齐操作，会立即提示对齐完成，但实际没有执行，
log中显示

```
==========2024-01-04_03:42:02==========
==========TimeStample_Alignment==========

UPdata DataModel
```

内存显存都有很大的空闲，网络也是全局挂的梯子

**Comment by CheshireCC** [comment]
这是一个 whisperX 的已知 bug，主要是由于对齐的某些段落中有多个人同时说话或者存在 whisper 的转录幻觉时就会发生，通过 提高 VAD 阈值尽可能过滤静音段，通过转录参数修正比如重复惩罚、空白抑制、修改温度（可能导致卸载 whisper 模型崩溃）、关闭循环提示 等手段抑制幻听 可以有效防止该 bug 发生

**Comment by CheshireCC** [comment]
新的问题请尽量使用新的 issue

**Comment by FreemanZ** [comment]
> 新的问题请尽量使用新的 issue


感谢回复，已经基本能用了，
还没玩清楚github（捂脸），您多包涵。
