### ISSUE TITLE
你好，作者，感谢你的付出！

### ISSUE THREAD

**Issue by energy7758** [CheshireCC/faster-whisper-GUI#52]
我发现在我用这个软件的时候，油管下载的MP4视频，用V3大模型，音频语言需要指定 en-english。不然会出现类似其它阿拉伯数字的语种..已开启使用V3模型选项。

**Comment by energy7758** [comment]
纠正以下，看来我英语水平太低了，还有个威尔士语，跟俚语一样的符号...

**Comment by CheshireCC** [comment]
v3模型可能会有这样的问题，我也认为稳定性不如v2，但是因为v3模型扩充了训练资料，所以可能适应性更广
