### ISSUE TITLE
用0.5的patch文件覆盖原来的文件后，就无法启动了

### ISSUE THREAD

**Issue by meowlgm** [CheshireCC/faster-whisper-GUI#53]
Windows 11系统，覆盖前可以正常使用。

**Comment by CheshireCC** [comment]
0.5 patch 是0.5.0版本的修复，建议卸载之后安装0.5.0版本

**Comment by meowlgm** [comment]
> 0.5 patch 是0.5.0版本的修复，建议卸载之后安装0.5.0版本

我安装的就是0.5版本，然后用的0.5的patch

**Comment by CheshireCC** [comment]
看下log文件吧

**Comment by CheshireCC** [comment]
太长时间没有回应，现在将关闭该 isssue
