### ISSUE TITLE
wav格式的音频会提示没有音频流

### ISSUE THREAD

**Issue by sqsq37** [CheshireCC/faster-whisper-GUI#55]
请问是BUG还是不支持
如果是后者的话希望能在之后的版本支持
WAV也算是常见的无损音频格式了

**Comment by CheshireCC** [comment]
wav一直支持，这个估计是处理音频文件的人使用的某些软件输出文件时丢失了元数据造成的，转成其他格式就行了，
另外近期可能有时间集中更新程序，音视频文件的检测逻辑可能会重新考虑

**Comment by CheshireCC** [comment]
如果能分享一下检测失败的文件供测试不胜感激

**Comment by sqsq37** [comment]
百度云分享吗还是

**Comment by CheshireCC** [comment]
> 百度云分享吗还是

百度云即可

**Comment by sqsq37** [comment]
百度云过期了，
https://www.asmr.one/works
这网站下的所有WAV都会显示没有音频流，还有其他地方下的类似性质的音声WAV都会这样，大佬麻烦下了测试吧，这网站直连下载的

**Comment by CheshireCC** [comment]
好的

**Comment by CheshireCC** [comment]
> 百度云过期了， https://www.asmr.one/works 这网站下的所有WAV都会显示没有音频流，还有其他地方下的类似性质的音声WAV都会这样，大佬麻烦下了测试吧，这网站直连下载的

我从这个网站下载了三四个 wav 格式的音频做测试，均能正常读取

**Comment by CheshireCC** [comment]
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/36411617/66225cd1-1bff-4941-830f-0900c3a5a070)

**Comment by sqsq37** [comment]
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/153402286/14bcf701-3d89-4bc6-aa97-5ab4adf5229e)
那我把有问题的开个百度云上传给你测试

**Comment by sqsq37** [comment]
链接：https://pan.baidu.com/s/1mKF-tWdhFSLxVmGtiUHcOQ?pwd=eiis 
提取码：eiis 
--来自百度网盘超级会员V1的分享

**Comment by CheshireCC** [comment]
好的

**Comment by CheshireCC** [comment]
经过测试，该问题已经查明，与文件格式无关。
该问题是由于异常的 tag 引起的，要避免该问题请清除包含非英文内容的 tag ，如：“艺术家”、“唱片集”等。
中、日文等非 Unicode 字符可能造成读取异常。

**Comment by CheshireCC** [comment]
将于下个版本进行修复

**Comment by CheshireCC** [comment]
0.5.4 已修复
