### ISSUE TITLE
无法在线加载v3模型

### ISSUE THREAD

**Issue by SpringHarbor** [CheshireCC/faster-whisper-GUI#57]
[fasterwhispergui.log](https://github.com/CheshireCC/faster-whisper-GUI/files/13801833/fasterwhispergui.log)

可否看一下log日志，每次都是加载失败

**Comment by CheshireCC** [comment]
faster-whisper 作者就职苹果公司的原因，相关 huggingface 存储库已经失去维护，所以暂时不能在线加载 V3 模型，项目首页提供了 32位 V3 模型的下载地址，包括 huggingface 和 百度云网盘的，可以下载到本地之后手动加载

**Comment by SpringHarbor** [comment]
下载了之后，本地加载依然出错，不知是哪有问题？


[fasterwhispergui.log](https://github.com/CheshireCC/faster-whisper-GUI/files/13804139/fasterwhispergui.log)

![PixPin_2024-01-01_20-48-45](https://github.com/CheshireCC/faster-whisper-GUI/assets/66197941/2c91ec40-d54a-4fda-84bb-e771ff6e0bae)

**Comment by CheshireCC** [comment]
显存不够了，把计算精度（即量化方式）改成 int8 吧，这个至少需要 8GB 显存可用才能加载 32位 large 模型，V3 模型的显存占用更高

**Comment by CheshireCC** [comment]
0.5.7 提供 V3 模型在线下载功能
