### ISSUE TITLE
能否同时保留源语言和英语翻译结果

### ISSUE THREAD

**Issue by xueli12** [CheshireCC/faster-whisper-GUI#64]
通过翻译软件进行翻译为中文时，不同源语言的翻译结果可能会略有差异，希望保留两个语言版本的字幕，这样方便比较和选取合适的翻译结果。
建议将程序的英语翻译结果作为一个额外输出的字幕，源语言的字幕仍保留。

**Comment by CheshireCC** [comment]
whisper 本身自带翻译功能，当强制翻译时直接输出翻译结果，没有原字幕可供保留
