### ISSUE TITLE
能推荐一个large-v2模型的下载链接吗？

### ISSUE THREAD

**Issue by xueli12** [CheshireCC/faster-whisper-GUI#65]
去hugging face下载了几个都加载不了 也不知道为啥。能推荐一个可以用的链接吗？

**Comment by CheshireCC** [comment]
模型必须下载完整，所有的配置文件都必须在模型文件夹内

链接：https://pan.baidu.com/s/13ewG2wyGVdNKo9_B6zbIqw?pwd=n9cw 
提取码：n9cw 
--来自百度网盘超级会员V9的分享

**Comment by xueli12** [comment]
> 模型必须下载完整，所有的配置文件都必须在模型文件夹内
> 
> 链接：https://pan.baidu.com/s/13ewG2wyGVdNKo9_B6zbIqw?pwd=n9cw 提取码：n9cw --来自百度网盘超级会员V9的分享

太感谢了 作者辛苦啦~
