### ISSUE TITLE
两个便利性建议

### ISSUE THREAD

**Issue by sqsq37** [CheshireCC/faster-whisper-GUI#66]
1 希望文件列表界面可以加一个一键清除文件列表的按键，框框选然后一直按减号太慢了

2拖动文件到列表添加这个操作希望可以支持拖动文件夹到文件列表然后自动识别文件夹里的所有音视频文件添加

**Comment by CheshireCC** [comment]
先码住，想码字的时候再说吧

**Comment by CheshireCC** [comment]
关于第一点，事实上你是可以在列表里使用 Ctrl+A 全选的

**Comment by CheshireCC** [comment]
0.5.7 已经全部实现
