### ISSUE TITLE
转写完成后程序闪退

### ISSUE THREAD

**Issue by anycall** [CheshireCC/faster-whisper-GUI#68]
程序在转写完成后突然闪退，再次打开程序在临时目录中找到转写完成的.srt文件（无其他格式的）；
打开日志文件检查，未见错误内容；
打开fast-whisper检查，日志文件无内容；

**Comment by anycall** [comment]
> 程序在转写完成后突然闪退，再次打开程序在临时目录中找到转写完成的.srt文件（无其他格式的）； 打开日志文件检查，未见错误内容； 打开fast-whisper检查，日志文件无内容；

补充：如果先执行了声乐移除的操作，再进行转写的操作，则不会闪退。

**Comment by CheshireCC** [comment]
窗体崩溃，如果开了转写完自动跳转的设置建议改成 询问或者不自动跳转
但也有可能是模型引起的崩溃，这个东西由于 CT2 引擎引起崩溃，这个 bug 由来已久，出现频率不高，也无法彻底修复。

**Comment by anycall** [comment]
> 窗体崩溃，如果开了转写完自动跳转的设置建议改成 询问或者不自动跳转 但也有可能是模型引起的崩溃，这个东西由于 CT2 引擎引起崩溃，这个 bug 由来已久，出现频率不高，也无法彻底修复。

补充：单个音频按照，声乐移除->转写->保存字幕，操作顺序，可以完成不会闪退；
目前看多个文件的情况的情况下，不管是什么顺序都会闪退，而且看不到日志的错误什么的。

**Comment by CheshireCC** [comment]
这个就是窗体崩溃了 ，你一次转写了多少个文件呢？

**Comment by anycall** [comment]
> 这个就是窗体崩溃了 ，你一次转写了多少个文件呢？

目前测试的情况是大于一个文件的情况下，就会崩溃

**Comment by CheshireCC** [comment]
好的，我将会进行测试

**Comment by CheshireCC** [comment]
经过相关测试，很难进行复现，现在暂时关闭相关 issue
