### ISSUE TITLE
提示框建议

### ISSUE THREAD

**Issue by Silverwolf-x** [CheshireCC/faster-whisper-GUI#70]
提示框建议自动消失（例如过5秒后渐变消失），而不是手动点击。或者可以留一个相关选项按钮提供选择。

![批注 2024-01-12 225514](https://github.com/CheshireCC/faster-whisper-GUI/assets/104623550/76069a45-116c-4ff4-859c-3559f437babd)

个人感觉手动点击着实有点麻烦...

**Comment by CheshireCC** [comment]
行吧，已经有几次相关 issue 了，
虽然我本来的设想不打算让它消失来着，
下次再更新的话就调整吧

**Comment by CheshireCC** [comment]
新版本中已经进行了修改，提示框 5 秒后将会自动消失
