### ISSUE TITLE
代码文件整理的建议

### ISSUE THREAD

**Issue by Silverwolf-x** [CheshireCC/faster-whisper-GUI#72]
感谢作者大大的无私奉献！现在faster-whisper-GUI文件下的python包等程序文件直接暴露在一级文件夹下，有一说一文件结构上还有整理的空间，比如一起打包丢在名为`python`文件夹下之类的。

下个版本更新时，有时间的话可以优化程序文件结构，如果实在太忙就算了吧（毕竟能跑就行（（

![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/104623550/7fc42cd2-70c6-4556-8a43-5566d81b5298)

**Comment by CheshireCC** [comment]
![mmexport1705057187319](https://github.com/CheshireCC/faster-whisper-GUI/assets/36411617/64a636bf-056b-4e9b-8ca5-37ee0a4ddc22)
