### ISSUE TITLE
开始后中途飙内存，直到爆，导致电脑卡死强制重启

### ISSUE THREAD

**Issue by 1353604736** [CheshireCC/faster-whisper-GUI#73]
400M大小7小时音频文件，开始后中途飙内存，直到爆内存，导致电脑卡死强制重启，重开后日志都刷没了
![微信图片_20240113203517](https://github.com/CheshireCC/faster-whisper-GUI/assets/12869582/d9396256-c355-409a-b7e6-f6c16c9089b3)

**Comment by CheshireCC** [comment]
7个小时时长的音频文件我从未处理过，也没有足够的数据可供测试，
建议拆分音频到2个小时之后分别处理
