### ISSUE TITLE
加载模型时显示加载失败

### ISSUE THREAD

**Issue by dzk457470350** [CheshireCC/faster-whisper-GUI#74]
本人纯小白，下载安装好本体后再下载模型到C盘，在加载后显示模型加载失败，求告知原因与解决方法~
![2024115233314](https://github.com/CheshireCC/faster-whisper-GUI/assets/85492627/77f6a0e7-cb44-4117-befb-807ca0f8cfc4)

**Comment by CheshireCC** [comment]
模型配置文件缺失了

**Comment by dzk457470350** [comment]
谢谢回答，我刚刚从已关闭的回答里找到了，正在重新尝试下载

**Comment by dzk457470350** [comment]
在尝试了关闭的问题中的解决方法后，依然没能解决问题
![QQ图片20240116000557](https://github.com/CheshireCC/faster-whisper-GUI/assets/85492627/1b602628-1848-4bff-bfa0-5480501562be)

**Comment by CheshireCC** [comment]
加载失败的时候去看看 日志文件

**Comment by dzk457470350** [comment]
-model_size_or_path: D:/backup/whisper-large-v2-ct2-32
    -device: cuda
    -device_index: 0
    -compute_type: float32
    -cpu_threads: 4
    -num_workers: 1
    -download_root: D:\FasterWhisperGUI\cache2
    -local_files_only: False
    -use_v3_model: False
Traceback (most recent call last):
  File "D:\FASTER~1\faster_whisper_GUI\modelLoad.py", line 41, in run
  File "D:\FASTER~1\faster_whisper_GUI\modelLoad.py", line 73, in loadModel
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 128, in __init__
RuntimeError: CUDA failed with error out of memory

**Comment by CheshireCC** [comment]
显存不够，你需要确保有至少 6GB 以上空闲显存才能加载 32 位模型，我发现你使用的是 int8 的模型，那么将量化方式改为 int8 吧

**Comment by dzk457470350** [comment]
对的 我显卡只有6GB显存 但是我不会将量化方式改为 int8  请问该如何操作

**Comment by CheshireCC** [comment]
计算精度那里选一下 
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/36411617/465fd976-9985-4504-a53e-e50346e5e961)

**Comment by dzk457470350** [comment]
模型加载成功！非常感谢！
![QQ图片20240116015541](https://github.com/CheshireCC/faster-whisper-GUI/assets/85492627/c77ee432-1619-44a4-899e-77f9baa5a895)

**Comment by chensuser** [comment]
想问下为什么我无法把hugging face下载下来的large v2直接丢进去当作模型？？
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/147965386/14d9d22c-6094-4a6d-8798-9c7cb9d7d037)
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/147965386/e7c593d7-65c2-4530-9637-bf27a997cd98)

**Comment by tomeleon** [comment]
我这里也是加载模型失败，日志显示是：
Traceback (most recent call last):
  File "C:\PROGRA~2\FasterWhisperGUI\faster_whisper_GUI\modelLoad.py", line 41, in run
  File "C:\PROGRA~2\FasterWhisperGUI\faster_whisper_GUI\modelLoad.py", line 73, in loadModel
  File "C:\PROGRA~2\FasterWhisperGUI\faster_whisper\transcribe.py", line 143, in __init__
Exception: Model "openai/whisper-tiny" on the Hub doesn't have a tokenizer

**Comment by CheshireCC** [comment]
检查模型文件夹下的文件是否完整
