### ISSUE TITLE
经常出现大段的遗漏，一段一段的转写不出来，每段遗漏从十几个字到上百个字不等。

### ISSUE THREAD

**Issue by running-frog** [CheshireCC/faster-whisper-GUI#75]
声音语速也不是很快，但仍然遗漏。软件界面做的很完美，但就是那些功能参数不知怎么调，按默认的参数就大段的漏转。

**Comment by running-frog** [comment]
Nvidia RTX3080 16G，系统内存32G，转写时，内存显存都用的不多，应该与配置无关吧？

**Comment by CheshireCC** [comment]
降低 VAD 阈值，语音环境复杂的情况下可先进行人声分离，
参数不会调我也没办法

**Comment by gsxgmpkt9020** [comment]
还有就是增加计算精度
