### ISSUE TITLE
麻烦可以写一个本地源码运行教程吗？新手！依赖包安装不全，版本不匹配。

### ISSUE THREAD

**Issue by jackcuishao** [CheshireCC/faster-whisper-GUI#76]

**Comment by CheshireCC** [comment]
emmm，我等调包侠
基本上就是反复运行那个主目录下的 fasterwhispergui.py文件等报错
缺哪个包就装哪个

**Comment by AiDreamerOoO** [comment]
> emmm，我等调包侠 基本上就是反复运行那个主目录下的fasterwhispergui.py文件等报错 缺哪个包就装哪个
大佬，运行fasterwhispergui.py之后没反应，是怎么回事也不提示报错什么的，就是没反应

**Comment by CheshireCC** [comment]
看 log 文件 ， fasterwhispergui.log 那里面有报错记录
