### ISSUE TITLE
希望可以加上强制简体中文或繁体中文的切换按钮

### ISSUE THREAD

**Issue by nanoTiO2** [CheshireCC/faster-whisper-GUI#77]
首先感谢作品大大的付出，很好的软件。当前的版本，无论是采取自动检测的方式还是手动指定Chinese中文的方式，在歌词和2小时左右视频的测试中，都存在着简体和繁体混合输出的情况。想烦扰作者朋友设置一个脚本或是前期代码输入，实现简体中文强制输出

```
20
00:02:20,530 --> 00:02:26,330
当那枫叶红菊花黄的时候

21
00:02:26,330 --> 00:02:31,250
我 数尽那山上的枫叶红

22
00:02:31,250 --> 00:02:34,890
数尽那山下的菊花开了

23
00:02:34,890 --> 00:02:38,130
我要回去 回去 回去

24
00:02:38,130 --> 00:02:42,210
回到你的怀抱里

25
00:02:42,210 --> 00:02:45,810
我知道你不會把我忘了

26
00:02:45,810 --> 00:02:49,410
我知道你當我默默照照

27
00:02:49,410 --> 00:02:56,810
隨著秋風 我奔向回頭

28
00:02:56,810 --> 00:03:00,610
如今那山上的楓葉紅了

29
00:03:00,610 --> 00:03:04,010
如今那山下的菊花開了

```

**Comment by CheshireCC** [comment]
简繁体需要转换才行，
【超级会员V9】通过百度网盘分享的文件：繁体简体字幕转换…
链接:https://pan.baidu.com/s/1dm5WGf9iObcuqpIr0SFxAg?pwd=162j 
提取码:162j
复制这段内容打开「百度网盘APP 即可获取」

这是一个转换工具

**Comment by running-frog** [comment]
只需要设置“提示文本”，比如“这是一段简体中文的录音。”，出来就是简体中文

**Comment by DaisyHunter** [comment]
> 简繁体需要转换才行， 【超级会员V9】通过百度网盘分享的文件：繁体简体字幕转换… 链接:[https://pan.baidu.com/s/1dm5WGf9iObcuqpIr0SFxAg?pwd=162j ](https://pan.baidu.com/s/1dm5WGf9iObcuqpIr0SFxAg?pwd=162j%C2%A0) 提取码:162j 复制这段内容打开「百度网盘APP 即可获取」
> 
> 这是一个转换工具

可以参考下这个[指定 Whisper 输出为简体中文](https://wulu.zone/posts/whisper-cn#:~:text=1%20%E4%BD%BF%E7%94%A8%20--initial_prompt%20%E5%8F%82%E6%95%B0%EF%BC%8C%E7%94%A8%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%E8%BE%93%E5%85%A5%20%22%E4%BB%A5%E4%B8%8B%E6%98%AF%E6%99%AE%E9%80%9A%E8%AF%9D%E7%9A%84%E5%8F%A5%E5%AD%90%E3%80%82%20%22%20%E5%B0%B1%E8%83%BD%E7%94%9F%E6%88%90%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%E3%80%82%20%EF%BC%88%E8%A1%A5%E5%85%85%EF%BC%9Awhisper.cpp,%E7%94%A8%E6%88%B7%E5%8F%AF%E4%BB%A5%E5%B0%9D%E8%AF%95%E4%BD%BF%E7%94%A8%20--prompt%20%E5%8F%82%E6%95%B0%EF%BC%89%202%20%E4%BB%A5%E6%AD%A4%E7%B1%BB%E6%8E%A8%EF%BC%8C%E7%94%A8%E7%B9%81%E4%BD%93%E4%B8%AD%E6%96%87%E8%BE%93%E5%85%A5%20%22%E4%BB%A5%E4%B8%8B%E6%98%AF%E6%99%AE%E9%80%9A%E8%A9%B1%E7%9A%84%E5%8F%A5%E5%AD%90%E3%80%82%20%22%20%E5%B0%B1%E8%83%BD%E5%BE%97%E5%88%B0%E7%B9%81%E4%BD%93%E5%AD%97%E5%B9%95%E3%80%82)

**Comment by powersee** [comment]
> 只需要设置“提示文本”，比如“这是一段简体中文的录音。”，出来就是简体中文

好像没用，我在【初始提示词】这里设置了，转换出来的还是繁体。

![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/38074760/7ebd68c1-93b7-4655-90fa-95a3220f18c5)

**Comment by CheshireCC** [comment]
初始提示词因该不是这么用的

**Comment by CheshireCC** [comment]
0.6.7 将提供简繁体中文选项
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/36411617/b9896701-d1c6-4ef4-a2d2-a1bc90523ce0)
