### ISSUE TITLE
可以增加转写标注功能吗？

### ISSUE THREAD

**Issue by hhucchenyixiao** [CheshireCC/faster-whisper-GUI#78]
给 https://github.com/RVC-Boss/GPT-SoVITS 或者 https://github.com/fishaudio/Bert-VITS2 使用，都需要把一堆切割后几秒短音频要按照`vocal_path|speaker_name|language|text` 转写到一个list里面。

**Comment by CheshireCC** [comment]
分割音频文件功能是有的，数据标注是另外一回事儿了，需要知道不同软件或者训练目的需要使用的标注文件格式，
这个我当时做的时候确实没考虑，先码住吧，等有时间了再说吧

**Comment by sqsq37** [comment]
附议，GPT-SoVITS自带的whisper转写性能太差了，几秒钟一句话的音频 largeV2能识别一两分钟，我怀疑他根本没调用GPU，如果作者能支持就再好不过了

**Comment by CheshireCC** [comment]
> 附议，GPT-SoVITS自带的whisper转写性能太差了，几秒钟一句话的音频 largeV2能识别一两分钟，我怀疑他根本没调用GPU，如果作者能支持就再好不过了

你们所说的标注功能是需要得到 csv 或者其他格式的标注文件吗？
音频文件分割功能其实已经有了，如果需要的话可以试试用脚本从文件名获取相关信息
如果该功能有需求的话也可以提供一个标注文件的格式，下个版本进行支持

**Comment by CheshireCC** [comment]
0.6.7 已经支持该功能
输出音频分段的时候将会在输出文件夹下包含 `csv` 格式的标注文件
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/36411617/d0ad0fa9-a0de-4c3d-b23f-f01a9b7b3904)
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/36411617/5b479678-3bde-47c6-a0f1-c0f795297b6f)
