### ISSUE TITLE
whisperx

### ISSUE THREAD

**Issue by dubr1k** [CheshireCC/faster-whisper-GUI#82]
How to get whole segments assigned to a speaker when using WhisperX Diarize? Attached is an example
![Снимок экрана 2024-01-30 182631](https://github.com/CheshireCC/faster-whisper-GUI/assets/146764463/89c44c92-6754-4a67-87c9-86680ff60965)

**Comment by CheshireCC** [comment]
If user take no interesting with timestamp ， this will be good

**Comment by dubr1k** [comment]
> If user take no interesting with timestamp ， this will be good

In a research paper, it is often the meaning that is important, not the time stamps. if possible, please add the output functionality in this form.

Thanks in advance!

**Comment by CheshireCC** [comment]
> > If user take no interesting with timestamp ， this will be good
> 
> In a research paper, it is often the meaning that is important, not the time stamps. if possible, please add the output functionality in this form.
> 
> Thanks in advance!

ok，when I be free ，I will update software to next version.

**Comment by dubr1k** [comment]
> > > If user take no interesting with timestamp ， this will be good
> 
> > 
> 
> > In a research paper, it is often the meaning that is important, not the time stamps. if possible, please add the output functionality in this form.
> 
> > 
> 
> > Thanks in advance!
> 
> 
> 
> ok，when I be free ，I will update software to next version.

Thank you! you are doing a very big job for students, sociologists, psychologists and journalists. I'm teaching you how to use your program!

**Comment by dubr1k** [comment]
Thx u!
