### ISSUE TITLE
V3模型的断句属实有问题，不知道是模型本身的问题还是参数

### ISSUE THREAD

**Issue by MrFutureV** [CheshireCC/faster-whisper-GUI#83]
![QQ截图20240131165923](https://github.com/CheshireCC/faster-whisper-GUI/assets/46783891/87857b6c-f644-403d-bb6b-eb1fc248e7d9)

**Comment by MrFutureV** [comment]
试过了V2和medium en也是同样的问题，参数是默认设置，相比与WhisperDesktop的项目感觉不怎么稳啊

**Comment by CheshireCC** [comment]
开启 vad 之后是这样的，调整 vad 参数可能会有帮助

**Comment by MrFutureV** [comment]
> 开启 vad 之后是这样的，调整 vad 参数可能会有帮助

关闭了vad效果也不尽人意，感觉还需要做很多优化

**Comment by bootlegseahorse** [comment]
在GUI里怎么关闭VAD啊 没有找到关闭的地方
