### ISSUE TITLE
无法加载模型

### ISSUE THREAD

**Issue by chinalong22** [CheshireCC/faster-whisper-GUI#84]
查看log文件，提示
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
torchvision is not available - cannot save figures
请问如何解决？

**Comment by xue160709** [comment]
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
torchvision is not available - cannot save figures
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.

faster_whisper_GUI: 0.5.7
==========2024-01-31_23:56:29==========
==========Start==========

language: zh

==========2024-01-31_23:56:31==========
==========LoadModel==========

    -model_size_or_path: D:/whisper-large-v3-float32
    -device: cuda
    -device_index: 0
    -compute_type: float32
    -cpu_threads: 4
    -num_workers: 1
    -download_root: C:/Users/xue16/.cache/huggingface/hub
    -local_files_only: False
    -use_v3_model: False

Load over
D:/whisper-large-v3-float32
max_length:             448
num_samples_per_token:  320
time_precision:  0.02
tokens_per_second:  50
input_stride:  2

==========2024-01-31_23:57:06==========
==========Process==========

redirect std output
vad_filter : True
    -threshold                : 0.5
    -min_speech_duration_ms   : 250
    -max_speech_duration_s    : inf
    -min_silence_duration_ms  : 2000
    -window_size_samples      : 1024
    -speech_pad_ms            : 400
Transcribes options:
    -audio : ['C:/Users/xue16/Downloads/AGIUI开源发布会.m4a']
    -language : None
    -task : False
    -beam_size : 5
    -best_of : 1
    -patience : 1.0
    -length_penalty : 1.0
    -temperature : [0.0]
    -compression_ratio_threshold : 2.4
    -log_prob_threshold : -1.0
    -no_speech_threshold : 0.6
    -condition_on_previous_text : False
    -initial_prompt : None
    -prefix : None
    -suppress_blank : True
    -suppress_tokens : [-1]
    -without_timestamps : False
    -max_initial_timestamp : 1.0
    -word_timestamps : False
    -prepend_punctuations : "'“¿([{-
    -append_punctuations : "'.。,，!！?？:：”)]}、
    -repetition_penalty : 1.0
    -no_repeat_ngram_size : 0
    -prompt_reset_on_temperature : 0.5
create transcribe process with 1 workers
start transcribe process
Traceback (most recent call last):
  File "D:\FASTER~1\faster_whisper_GUI\transcribe.py", line 354, in run
  File "D:\FASTER~1\concurrent\futures\_base.py", line 621, in result_iterator
  File "D:\FASTER~1\concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "D:\FASTER~1\concurrent\futures\_base.py", line 458, in result
  File "D:\FASTER~1\concurrent\futures\_base.py", line 403, in __get_result
  File "D:\FASTER~1\concurrent\futures\thread.py", line 58, in run
  File "D:\FASTER~1\faster_whisper_GUI\transcribe.py", line 226, in transcribe_file
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 327, in transcribe
  File "D:\FASTER~1\faster_whisper\transcribe.py", line 629, in encode
ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead
是不是跟你的一样？

**Comment by chinalong22** [comment]
一样的提示

**Comment by CheshireCC** [comment]
检查 v3 模型选项，不是v3模型不要开启该选项 是v3模型才使用该选项

**Comment by chinalong22** [comment]
跟V3模型选项无关，切换都是这个错误提示，请核实原因

**Comment by CheshireCC** [comment]
ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead

此处明确显示是梅尔滤波器组的大小的问题，由于 v3 模型差异引起的
