### ISSUE TITLE
关于转写的问题

### ISSUE THREAD

**Issue by matrix-sys** [CheshireCC/faster-whisper-GUI#85]
报错：“ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead”
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/65747037/e4e2e69b-aff8-4377-b324-5e2bc7dd16c8)
然后一直卡在正在处理，请问是什么原因~谢谢

**Comment by CheshireCC** [comment]
非 v3 模型需要在模型页面关闭相应选项，使用 large-v3 模型才开启该选项

**Comment by matrix-sys** [comment]
谢谢，解决了。

**Comment by matrix-sys** [comment]
补充：我使用了在线模式，medium模型后就正常了，关闭V3开关。
