### ISSUE TITLE
不能选择档案加载模型 是因为什么原因

### ISSUE THREAD

**Issue by chensuser** [CheshireCC/faster-whisper-GUI#88]
想问下为什么我无法把hugging face下载下来的large v2直接丢进去当作模型？？（新手小白完全不懂）
==========LoadModel==========

    -model_size_or_path: C:/Users/Superman/.cache/huggingface/hub/models--openai--whisper-large-v2
    -device: cuda
    -device_index: 0
    -compute_type: float32
    -cpu_threads: 4
    -num_workers: 1
    -download_root: C:/Users/Superman/.cache/huggingface/hub
    -local_files_only: True
    -use_v3_model: False
Traceback (most recent call last):
  File "E:\Whisper\FasterWhisperGUI\faster_whisper_GUI\modelLoad.py", line 41, in run
  File "E:\Whisper\FasterWhisperGUI\faster_whisper_GUI\modelLoad.py", line 73, in loadModel
  File "E:\Whisper\FasterWhisperGUI\faster_whisper\transcribe.py", line 130, in __init__
RuntimeError: Unable to open file 'model.bin' in model 'C:/Users/Superman/.cache/huggingface/hub/models--openai--whisper-large-v2'

我用在线下载的模型翻译到53秒出现了不是我预期的口语字幕
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/147965386/b1c101af-8670-45ef-a267-efc45e0f6b3b)
而接下来到完结了之后都是变成口语

**Comment by CheshireCC** [comment]
从 HF 下载的模型必须保证全部模型文件包含配置文件都下载完整并且后缀名正确，然后每个模型的文件单独放在一个文件夹内，不能有子目录，加载模型的时候选择模型文件所在文件夹

粤方言的话 large-V3 模型将会有专门的语言选项 `yue` ，效果也有所提升

**Comment by chensuser** [comment]
我想说为什么不能设置那个界面能看见正在加载的模型是什么名字或者他的路径吗
在强制对齐那部分我希望可以用我再hugging Face下载下来的模型进行强制对齐 因为我试过那个好像比较好（预设没有侦测到广东话那么完整）

**Comment by CheshireCC** [comment]
时间戳对齐是由 whisperX 内核提供的，更换模型需要重写内核才行

**Comment by chensuser** [comment]
请问有另外途径可以联系你到吗  我其实真的很想用那个模型 我摸索了很久可是因为我是新手我完全不知道怎么办 我弄到了模型可是卡在这一步

在 2024年2月14日週三 18:20，Cheshire ***@***.***> 寫道：

**Comment by CheshireCC** [comment]
邮件请发 zpbzys@163.com

**Comment by CheshireCC** [comment]
已经添加 针对粤语的 whisperX 模型
