### ISSUE TITLE
语音中人声间隔3-5分钟以上，请问设置哪里可以提高字幕语句时长精度

### ISSUE THREAD

**Issue by yczhwei** [CheshireCC/faster-whisper-GUI#89]
请问，语音中人声有间隔 3、5，8分钟以上，字幕时间轴不能精确切断
请问设置哪里可以提高字幕语句时长精度

**Comment by CheshireCC** [comment]
这个时候可以打开单词级时间戳，一定程度上会有帮助，
使用whisper X 对齐字幕时间戳会有帮助
参数方面调整 vad 参数的时间间隔或者静息时长等参数会有帮助
