### ISSUE TITLE
好像直接选择mkv文件无法识别语音文件 可以加上mkv的识别吗

### ISSUE THREAD

**Issue by chrisluwtw** [CheshireCC/faster-whisper-GUI#90]
mkv里的音频文件无法被识别

**Comment by CheshireCC** [comment]
什么原因呢？能描述更详细吗？或者方便的话提供数据进行一下测试

**Comment by chrisluwtw** [comment]
就是选择mkv文件都说不含音频流 我用了几个mkv文件都不行 但是用原生的open ai whisper跑没有问题
<img width="906" alt="image" src="https://github.com/CheshireCC/faster-whisper-GUI/assets/83245014/52a99970-36e1-49f9-8597-12a031c942da">

**Comment by chrisluwtw** [comment]
我查看了一下 这些mkv里面包含了字幕文件 是不是会影响？

**Comment by chrisluwtw** [comment]
链接：https://pan.baidu.com/s/1uRbNRLtdJfTRzECHUId8yQ?pwd=tpto 
提取码：tpto 
--来自百度网盘超级会员V9的分享 这个是其中一个文件

**Comment by FreemanZ** [comment]
用OBS批量转一下封装试试，
![image](https://github.com/CheshireCC/faster-whisper-GUI/assets/7681383/95b438a2-b03c-46f7-986e-2f6e11b9547d)

**Comment by CheshireCC** [comment]
好的，感谢

**Comment by CheshireCC** [comment]
已经查明，确实是字幕问题造成的，

**Comment by CheshireCC** [comment]
但是这都已经有字幕了，还识别个毛线啊😑

**Comment by chrisluwtw** [comment]
> 但是这都已经有字幕了，还识别个毛线啊😑

其实即使有字幕有时候还是需要 比如说日剧韩剧美剧只有中文字幕 但是想看原始语音字幕

**Comment by CheshireCC** [comment]
> > 但是这都已经有字幕了，还识别个毛线啊😑
> 
> 其实即使有字幕有时候还是需要 比如说日剧韩剧美剧只有中文字幕 但是想看原始语音字幕

将于下个版本修复

**Comment by CheshireCC** [comment]
已经修复

**Comment by acewuwan** [comment]
请问我为什么用wav格式的音频文件不行
