### ISSUE TITLE
Strings for translate to English and Spanish 

### ISSUE THREAD

**Issue by johnfelipe** [CheshireCC/faster-whisper-GUI#92]

**Comment by CheshireCC** [comment]
I can't understand

**Comment by johnfelipe** [comment]
I want to contribute for have UI in English and Spanish, tell me where is
strings for translate and do PR

**Comment by CheshireCC** [comment]
You can use Engish UI， set UI language in setting Page
if you want to translate SP ， you just need open en.ts file with pyside6-linguist, and then translate and save as another fileName just like sp.ts, this file can also be released as sp.qm file that an be used in software.
