### ISSUE TITLE
Could not open on Win11

### ISSUE THREAD

**Issue by lilei105** [CheshireCC/faster-whisper-GUI#95]
安装完成后，运行fasterwhispergui.exe无反应，没有报错，没有弹窗，Event Viewer里也没有信息。重启过，卸载重装过，依旧。试了0.60和0.67都是这样。。。
环境：
Windows 11 23H2
4090 驱动31.0.15.4633

**Comment by CheshireCC** [comment]
看看日志文件
fasterwhisperGUI.log

**Comment by lilei105** [comment]
> 看看日志文件 fasterwhisperGUI.log

谢谢，但是搜了目录没发现这个文件啊？

**Comment by lilei105** [comment]
特意去虚拟机里又装了一遍，也是这样，安装以后运行.exe毫无反应=_=

**Comment by lilei105** [comment]
啊这……原来如此，必须得管理员权限启动才行，多谢多谢

**Comment by nzky0** [comment]
> 那说明程序没有启动成功，运行程序之后看看任务管理器有没有这个进程，没有的话说明运行失败了 试一下用管理员权限启动，

您好，確實有這個問題，需要管理員權限運行，安裝在非C盤目錄下則不會出現這個情況，這不是我第一次遇到這個情況了。

**Comment by CheshireCC** [comment]
程序被安装在了需要管理员权限的硬盘下，因为程序启动需要读写一些文件，
尽量把程序安装到非管理员权限的硬盘下，因为管理员权限运行时文件拖放功能会失效
