### ISSUE TITLE
TimeStample alignment failed.  How to fix it?

### ISSUE THREAD

**Issue by bk111** [CheshireCC/faster-whisper-GUI#98]
I have download  the file and put it to C:\Users\dengz\.cache\wav2vec2_fairseq_base_ls960_asr_ls960.pth

==========TimeStample_Alignment==========

TimeStample alignment
transform transcript result...
process audio...
load wav2vec2 model...
alignment Error
**Error: PytorchStreamReader failed reading zip archive: failed finding central directory**
UPdata DataModel

**Comment by bk111** [comment]
fixed.
the dir should be H:\FasterWhisperGUI\cache\wav2vec2_fairseq_base_ls960_asr_ls960.pth, not C:\Users\dengz.cache\wav2vec2_fairseq_base_ls960_asr_ls960.pth.
first del the bad *.pth, then download again or put the new pth to C:\Users\dengz.cache\

**Comment by CheshireCC** [comment]
So , you reset `download_root` path to `H:\FasterWhisperGUI\cache\` ?

**Comment by bk111** [comment]
> So , you reset `download_root` path to `H:\FasterWhisperGUI\cache\` ?

no.  download_root path is C:/Users/dengz/.cache/huggingface/hub , at last put pth to H:\FasterWhisperGUI\cache

maybe you need test more cases for this function.

**Comment by CheshireCC** [comment]
ok...

**Comment by CheshireCC** [comment]
OK, I found that `download_root ` only be used for faster-whisper model download.
